FORMAT: 1A

+ Response 200 (application/json)

# [/api/predict/bigdata]
## BigDataPredict [POST]

{'code': 200,
 'data': {'graphData': [{'xName': '1', 'yValue': 214},
                        {'xName': '2', 'yValue': 756},
                        {'xName': '3', 'yValue': 846},
                        {'xName': '4', 'yValue': 258},
                        {'xName': '5', 'yValue': 164},
                        {'xName': '6', 'yValue': 62},
                        {'xName': '7', 'yValue': 864},
                        {'xName': '8', 'yValue': 473},
                        {'xName': '9', 'yValue': 584},
                        {'xName': '10', 'yValue': 402},
                        {'xName': '11', 'yValue': 158},
                        {'xName': '12', 'yValue': 754},
                        {'xName': '13', 'yValue': 662},
                        {'xName': '14', 'yValue': 717},
                        {'xName': '15', 'yValue': 14},
                        {'xName': '16', 'yValue': 319},
                        {'xName': '17', 'yValue': 955}],
          'tableOneData': [{'index': '评价指标 1',
                            'mape': 0.5503968357713964,
                            'r2': 0.5348088087428792,
                            'rmse': 0.8935189139695968},
                           {'index': '评价指标 2',
                            'mape': 0.7284635479208729,
                            'r2': 0.926494096164709,
                            'rmse': 0.8916736468532448},
                           {'index': '评价指标 3',
                            'mape': 0.47172230220146816,
                            'r2': 0.015294041777146106,
                            'rmse': 0.2690937264832083},
                           {'index': '评价指标 4',
                            'mape': 0.3281462110797463,
                            'r2': 0.4057852621848299,
                            'rmse': 0.1461283263470513},
                           {'index': '评价指标 5',
                            'mape': 0.45967649622291995,
                            'r2': 0.49212191381387393,
                            'rmse': 0.1062607120652258},
                           {'index': '评价指标 6',
                            'mape': 0.21731610244514887,
                            'r2': 0.32315372425884425,
                            'rmse': 0.7972814985412483},
                           {'index': '评价指标 7',
                            'mape': 0.7824712239419209,
                            'r2': 0.19855552438030644,
                            'rmse': 0.2662162320495671},
                           {'index': '评价指标 8',
                            'mape': 0.4310504614078118,
                            'r2': 0.06137851460410593,
                            'rmse': 0.5154450616788806},
                           {'index': '评价指标 9',
                            'mape': 0.9633674811093258,
                            'r2': 0.8971359133657866,
                            'rmse': 0.14547091676853752},
                           {'index': '评价指标 10',
                            'mape': 0.12571115820400358,
                            'r2': 0.9791541400164899,
                            'rmse': 0.5112000978955618},
                           {'index': '评价指标 11',
                            'mape': 0.4626769678202496,
                            'r2': 0.6494143367839571,
                            'rmse': 0.8408976874398952},
                           {'index': '评价指标 12',
                            'mape': 0.4897152485081804,
                            'r2': 0.8966917506881885,
                            'rmse': 0.6650881821151309},
                           {'index': '评价指标 13',
                            'mape': 0.8343745200613326,
                            'r2': 0.512121508104869,
                            'rmse': 0.179126986600743},
                           {'index': '评价指标 14',
                            'mape': 0.34015498295218516,
                            'r2': 0.3453843366180436,
                            'rmse': 0.5754417570652688},
                           {'index': '评价指标 15',
                            'mape': 0.45884060441863506,
                            'r2': 0.6881872193747142,
                            'rmse': 0.12111360888114964},
                           {'index': '评价指标 16',
                            'mape': 0.26167773786710335,
                            'r2': 0.09890827519519718,
                            'rmse': 0.9922908779016265},
                           {'index': '评价指标 17',
                            'mape': 0.9289841479281707,
                            'r2': 0.7063232588360516,
                            'rmse': 0.08248798645465238}],
          'tableTwoData': [{'predict': 17.897858739268827, 'year': 2010},
                           {'predict': 75.647715137553, 'year': 2011},
                           {'predict': 377.00777201821097, 'year': 2012},
                           {'predict': 96.69114906915313, 'year': 2013},
                           {'predict': 291.28817809527106, 'year': 2014},
                           {'predict': 183.78432695413912, 'year': 2015},
                           {'predict': 408.4720846766973, 'year': 2016},
                           {'predict': 402.9160083477588, 'year': 2017},
                           {'predict': 387.92145698053173, 'year': 2018},
                           {'predict': 90.73567067231629, 'year': 2019},
                           {'predict': 209.7104186280784, 'year': 2020},
                           {'predict': 32.425795163148436, 'year': 2021},
                           {'predict': 265.00160212349175, 'year': 2022},
                           {'predict': 128.56318160717532, 'year': 2023},
                           {'predict': 228.26046902416925, 'year': 2024},
                           {'predict': 310.6975759994327, 'year': 2025},
                           {'predict': 327.22267162519694, 'year': 2026}]},
 'msg': 'success'}
