FORMAT: 1A

+ Response 200 (application/json)

# [/api/predict/bigdata]
## BigDataPredict [POST]

{'code': 200,
 'data': {'graphData': [{'xName': '1', 'yValue': 120},
                        {'xName': '2', 'yValue': 752},
                        {'xName': '3', 'yValue': 30},
                        {'xName': '4', 'yValue': 351},
                        {'xName': '5', 'yValue': 215},
                        {'xName': '6', 'yValue': 906},
                        {'xName': '7', 'yValue': 596},
                        {'xName': '8', 'yValue': 526},
                        {'xName': '9', 'yValue': 537},
                        {'xName': '10', 'yValue': 99},
                        {'xName': '11', 'yValue': 541},
                        {'xName': '12', 'yValue': 931},
                        {'xName': '13', 'yValue': 652},
                        {'xName': '14', 'yValue': 4},
                        {'xName': '15', 'yValue': 404},
                        {'xName': '16', 'yValue': 356},
                        {'xName': '17', 'yValue': 636}],
          'tableOneData': [{'index': '评价指标 1',
                            'mape': 0.954792370203407,
                            'r2': 0.14792690742755166,
                            'rmse': 0.3514266887792855},
                           {'index': '评价指标 2',
                            'mape': 0.007845199792056778,
                            'r2': 0.6629519952378385,
                            'rmse': 0.15723319214766163},
                           {'index': '评价指标 3',
                            'mape': 0.0721557580239659,
                            'r2': 0.8147787330031976,
                            'rmse': 0.43145271431735177},
                           {'index': '评价指标 4',
                            'mape': 0.49590754940895676,
                            'r2': 0.15682950922686334,
                            'rmse': 0.9019995935826897},
                           {'index': '评价指标 5',
                            'mape': 0.6484166045509933,
                            'r2': 0.41669705477163776,
                            'rmse': 0.4412033797996837},
                           {'index': '评价指标 6',
                            'mape': 0.5737390674228883,
                            'r2': 0.08033854583891675,
                            'rmse': 0.5738890187076275},
                           {'index': '评价指标 7',
                            'mape': 0.15761577734799126,
                            'r2': 0.5748212229746891,
                            'rmse': 0.974304422853411},
                           {'index': '评价指标 8',
                            'mape': 0.5700812865993486,
                            'r2': 0.31719273806797255,
                            'rmse': 0.2485492241241073},
                           {'index': '评价指标 9',
                            'mape': 0.5333846622773819,
                            'r2': 0.8148880803933947,
                            'rmse': 0.5371024455583759},
                           {'index': '评价指标 10',
                            'mape': 0.06687904897329178,
                            'r2': 0.2627631440871021,
                            'rmse': 0.9343972819307177},
                           {'index': '评价指标 11',
                            'mape': 0.21416721355112855,
                            'r2': 0.33040424349175834,
                            'rmse': 0.31936523385948623},
                           {'index': '评价指标 12',
                            'mape': 0.004334398307883625,
                            'r2': 0.3190757172738419,
                            'rmse': 0.034465507777900806},
                           {'index': '评价指标 13',
                            'mape': 0.9837638476447836,
                            'r2': 0.9053597656999421,
                            'rmse': 0.3877312678537065},
                           {'index': '评价指标 14',
                            'mape': 0.6199881959399637,
                            'r2': 0.3593793658522634,
                            'rmse': 0.9851248696870971},
                           {'index': '评价指标 15',
                            'mape': 0.39661791467932317,
                            'r2': 0.3833370971045731,
                            'rmse': 0.5841613750287397},
                           {'index': '评价指标 16',
                            'mape': 0.5299463289903243,
                            'r2': 0.7599900158643468,
                            'rmse': 0.5810766109377683},
                           {'index': '评价指标 17',
                            'mape': 0.1530046679087369,
                            'r2': 0.1340946878215462,
                            'rmse': 0.634493588785547}],
          'tableTwoData': [{'predict': 365.6776701180075, 'year': 2010},
                           {'predict': 337.58299124464656, 'year': 2011},
                           {'predict': 21.039817850604656, 'year': 2012},
                           {'predict': 111.37796267186884, 'year': 2013},
                           {'predict': 28.970615063915027, 'year': 2014},
                           {'predict': 278.06789258089236, 'year': 2015},
                           {'predict': 317.1808687687798, 'year': 2016},
                           {'predict': 57.21248938835196, 'year': 2017},
                           {'predict': 124.08729909972003, 'year': 2018},
                           {'predict': 63.13032720328691, 'year': 2019},
                           {'predict': 194.43658489564066, 'year': 2020},
                           {'predict': 257.4538939980657, 'year': 2021},
                           {'predict': 60.36567206961569, 'year': 2022},
                           {'predict': 274.22512034154806, 'year': 2023},
                           {'predict': 127.70996549507592, 'year': 2024},
                           {'predict': 198.10941199613137, 'year': 2025},
                           {'predict': 85.93278542440763, 'year': 2026}]},
 'msg': 'success'}
