FORMAT: 1A

+ Response 200 (application/json)

# [/api/predict/bigdata]
## BigDataPredict [POST]

{'code': 200,
 'data': {'graphData': [{'xName': '1', 'yValue': 634},
                        {'xName': '2', 'yValue': 661},
                        {'xName': '3', 'yValue': 840},
                        {'xName': '4', 'yValue': 701},
                        {'xName': '5', 'yValue': 676},
                        {'xName': '6', 'yValue': 358},
                        {'xName': '7', 'yValue': 601},
                        {'xName': '8', 'yValue': 328},
                        {'xName': '9', 'yValue': 671},
                        {'xName': '10', 'yValue': 591},
                        {'xName': '11', 'yValue': 115},
                        {'xName': '12', 'yValue': 214},
                        {'xName': '13', 'yValue': 576},
                        {'xName': '14', 'yValue': 437},
                        {'xName': '15', 'yValue': 755},
                        {'xName': '16', 'yValue': 555},
                        {'xName': '17', 'yValue': 679}],
          'tableOneData': [{'index': '评价指标 1',
                            'mape': 0.8195784097316954,
                            'r2': 0.30688238854623884,
                            'rmse': 0.5645912020962944},
                           {'index': '评价指标 2',
                            'mape': 0.28809375658482117,
                            'r2': 0.8846952445101705,
                            'rmse': 0.4768766741530911},
                           {'index': '评价指标 3',
                            'mape': 0.4605725523436106,
                            'r2': 0.10321547211192394,
                            'rmse': 0.31322429881623237},
                           {'index': '评价指标 4',
                            'mape': 0.5082685433783537,
                            'r2': 0.12587101375848986,
                            'rmse': 0.8957876600055067},
                           {'index': '评价指标 5',
                            'mape': 0.9822398176811286,
                            'r2': 0.291395311474385,
                            'rmse': 0.8336571437383399},
                           {'index': '评价指标 6',
                            'mape': 0.34435447479153514,
                            'r2': 0.7232779440868163,
                            'rmse': 0.10518377848537463},
                           {'index': '评价指标 7',
                            'mape': 0.45549793375776426,
                            'r2': 0.09247190753445589,
                            'rmse': 0.9841168142766823},
                           {'index': '评价指标 8',
                            'mape': 0.8293199934369119,
                            'r2': 0.9897816290281711,
                            'rmse': 0.3051850880648326},
                           {'index': '评价指标 9',
                            'mape': 0.04906409289058489,
                            'r2': 0.6493668372455925,
                            'rmse': 0.47009164996567143},
                           {'index': '评价指标 10',
                            'mape': 0.9127951996791063,
                            'r2': 0.4471549291995648,
                            'rmse': 0.18570271464819976},
                           {'index': '评价指标 11',
                            'mape': 0.5057937128831407,
                            'r2': 0.3936097440492362,
                            'rmse': 0.656421451006137},
                           {'index': '评价指标 12',
                            'mape': 0.10459331325103194,
                            'r2': 0.04288161157187231,
                            'rmse': 0.9634742160201649},
                           {'index': '评价指标 13',
                            'mape': 0.26856690638307135,
                            'r2': 0.7113695737252542,
                            'rmse': 0.2844034571431241},
                           {'index': '评价指标 14',
                            'mape': 0.7341188227312246,
                            'r2': 0.7451017910165069,
                            'rmse': 0.05343751063216484},
                           {'index': '评价指标 15',
                            'mape': 0.24744167908255577,
                            'r2': 0.5484566831211551,
                            'rmse': 0.08138695009827146},
                           {'index': '评价指标 16',
                            'mape': 0.9922441582514714,
                            'r2': 0.6164025945716992,
                            'rmse': 0.9482880938342243},
                           {'index': '评价指标 17',
                            'mape': 0.032877012419741614,
                            'r2': 0.1462186698441721,
                            'rmse': 0.09825186652326323}],
          'tableTwoData': [{'predict': 93.65036254411665, 'year': 2010},
                           {'predict': 20.078658791120855, 'year': 2011},
                           {'predict': 354.41067948584913, 'year': 2012},
                           {'predict': 273.77470524961, 'year': 2013},
                           {'predict': 352.16397806563043, 'year': 2014},
                           {'predict': 295.1081513275634, 'year': 2015},
                           {'predict': 77.85926712560295, 'year': 2016},
                           {'predict': 176.34382211377095, 'year': 2017},
                           {'predict': 96.3117975961778, 'year': 2018},
                           {'predict': 68.42903321511953, 'year': 2019},
                           {'predict': 130.4579678075646, 'year': 2020},
                           {'predict': 365.26999751180756, 'year': 2021},
                           {'predict': 268.7899525722774, 'year': 2022},
                           {'predict': 251.95407633515535, 'year': 2023},
                           {'predict': 127.54360260868607, 'year': 2024},
                           {'predict': 10.896060895672049, 'year': 2025},
                           {'predict': 223.7564043523222, 'year': 2026}]},
 'msg': 'success'}
