FORMAT: 1A

+ Response 200 (application/json)

# [/api/params/predict/biguser]
## BigUserPredictionParameters [GET]

{'code': 200,
 'data': {'beginYear': 1994,
          'endYear': 2004,
          'historyBeginYear': 1966,
          'historyEndYear': 1997,
          'method': '测试方法',
          'patches': [{'grain': '粒度（总是「年」）',
                       'metaData': ['a', 'b', 'c'],
                       'value': '42',
                       'year': '年份'},
                      '...'],
          'region': '测试地域'},
 'msg': 'success'}
