FORMAT: 1A

+ Response 200 (application/json)

# [/api/params/predict/biguser]
## BigUserPredictionParameters [GET]

{'code': 200,
 'data': {'beginYear': 0,
          'endYear': 0,
          'historyBeginYear': 0,
          'historyEndYear': 0,
          'method': '',
          'patches': [{'grain': '粒度（总是「年」）',
                       'metaData': ['a', 'b', 'c'],
                       'value': '42',
                       'year': '年份'},
                      Ellipsis],
          'region': ''},
 'msg': 'success'}
