FORMAT: 1A

+ Response 200 (application/json)

# [/api/payload/predict/clamping]
## ClampingPayloadPredict [POST]

{'code': 200,
 'data': [{'actualPayload': 212554, 'predictPayload': 382494, 'time': '16:22'},
          {'actualPayload': 478034, 'predictPayload': 893773, 'time': '19:44'},
          {'actualPayload': 280149, 'predictPayload': 839141, 'time': '15:18'},
          {'actualPayload': 12450, 'predictPayload': 671864, 'time': '16:29'},
          {'actualPayload': 945604, 'predictPayload': 871273, 'time': '16:38'},
          {'actualPayload': 113604, 'predictPayload': 272322, 'time': '14:24'},
          {'actualPayload': 869087, 'predictPayload': 465791, 'time': '11:14'},
          {'actualPayload': 729909, 'predictPayload': 157597, 'time': '19:25'},
          {'actualPayload': 405806, 'predictPayload': 969085, 'time': '18:16'},
          {'actualPayload': 741966, 'predictPayload': 518311, 'time': '20:50'},
          {'actualPayload': 978782, 'predictPayload': 180358, 'time': '10:11'},
          {'actualPayload': 204492, 'predictPayload': 183289, 'time': '20:13'}],
 'msg': 'success'}
