FORMAT: 1A

+ Response 200 (application/json)

# [/api/payload/predict/clamping]
## ClampingPayloadPredict [POST]

{'code': 200,
 'data': [{'actualPayload': 622047, 'predictPayload': 629062, 'time': '14:27'},
          {'actualPayload': 553945, 'predictPayload': 125063, 'time': '16:45'},
          {'actualPayload': 377048, 'predictPayload': 959307, 'time': '15:13'},
          {'actualPayload': 821811, 'predictPayload': 130133, 'time': '20:33'},
          {'actualPayload': 963487, 'predictPayload': 134763, 'time': '13:43'},
          {'actualPayload': 721006, 'predictPayload': 53936, 'time': '17:25'},
          {'actualPayload': 514110, 'predictPayload': 974147, 'time': '16:25'},
          {'actualPayload': 152696, 'predictPayload': 60239, 'time': '14:35'},
          {'actualPayload': 503101, 'predictPayload': 318954, 'time': '17:27'},
          {'actualPayload': 869658, 'predictPayload': 501417, 'time': '17:32'},
          {'actualPayload': 666150, 'predictPayload': 822708, 'time': '15:15'},
          {'actualPayload': 906406, 'predictPayload': 316070, 'time': '16:37'}],
 'msg': 'success'}
