FORMAT: 1A

+ Response 200 (application/json)

# [/api/payload/predict/clamping]
## ClampingPayloadPredict [POST]

{'code': 200,
 'data': [{'actualPayload': 227943, 'predictPayload': 546692, 'time': '15:27'},
          {'actualPayload': 708517, 'predictPayload': 494563, 'time': '16:20'},
          {'actualPayload': 57748, 'predictPayload': 879231, 'time': '15:27'},
          {'actualPayload': 771875, 'predictPayload': 400529, 'time': '17:49'},
          {'actualPayload': 565406, 'predictPayload': 467162, 'time': '15:22'},
          {'actualPayload': 997452, 'predictPayload': 860094, 'time': '15:14'},
          {'actualPayload': 654506, 'predictPayload': 905278, 'time': '11:20'},
          {'actualPayload': 949322, 'predictPayload': 37490, 'time': '20:20'},
          {'actualPayload': 705975, 'predictPayload': 322481, 'time': '20:25'},
          {'actualPayload': 591272, 'predictPayload': 39681, 'time': '12:27'},
          {'actualPayload': 691986, 'predictPayload': 239579, 'time': '12:11'},
          {'actualPayload': 375717, 'predictPayload': 349080, 'time': '19:46'}],
 'msg': 'success'}
