FORMAT: 1A

+ Response 200 (application/json)

# [/api/params/predict/clamping]
## ClampingPayloadPredictionParameters [GET]

{'code': 200,
 'data': {'beginYear': 2021,
          'dailyAmount': 155,
          'endYear': 2022,
          'maxPayload': 2013,
          'season': 3},
 'msg': 'success'}
