FORMAT: 1A

+ Response 200 (application/json)

# [/api/params/predict/dynamic/industry]
## DynamicIndustrialPredictionParameters [GET]

{'code': 200,
 'data': {'beginYear': 0,
          'endYear': 0,
          'historyBeginYear': 0,
          'historyEndYear': 0,
          'industry': '',
          'method': '',
          'parameters': ['paramA', 'paramB', Ellipsis]},
 'msg': 'success'}
