FORMAT: 1A

+ Response 200 (application/json)

# [/api/params/predict/dynamic/industry]

## DynamicIndustrialPredictionParameters [GET]

{'code': 200,
 'data': {'beginYear': 1995,
          'endYear': 2006,
          'historyBeginYear': 2012,
          'historyEndYear': 2055,
          'industry': '行业',
          'method': '方法',
          'parameters': ['paramA', 'paramB', '...']},
 'msg': 'success'}
