FORMAT: 1A

+ Response 200 (application/json)

# [/api/db/except/query]
## ExceptionQuery [POST]

{'code': 200,
 'data': [{'category': ['三', '1', 'iv'],
           'grain': '天',
           'key': '2021-1-8',
           'suggest': 42,
           'value': 10},
          {'category': ['三', '1', 'i'],
           'grain': '年',
           'key': '2021-1-7',
           'suggest': '蔡翠菊',
           'value': '杨咏曼'},
          {'category': ['三', '2', 'iii'],
           'grain': '秒',
           'key': '2021-1-5',
           'suggest': 2.718281828,
           'value': 3.141592653589},
          {'category': ['四', '2', 'ii'],
           'grain': '年',
           'key': '2021-1-3',
           'suggest': False,
           'value': True}],
 'msg': 'success'}
