FORMAT: 1A

+ Response 200 (application/json)

# [/api/predict/history/query]
## HistoryPredictionQuery [GET]

{'code': 200,
 'data': [{'amount': 10,
           'id': UUID('d7e21775-23e4-326f-91ae-54e2b3fdafde'),
           'time': '2020 年 1 月 1 日 01:01:01',
           'type': '电力预测'},
          {'amount': 10,
           'id': UUID('d7e21775-23e4-326f-91ae-54e2b3fdafde'),
           'time': '2020 年 2 月 2 日 02:02:02',
           'type': '电力预测'},
          {'amount': 10,
           'id': UUID('d7e21775-23e4-326f-91ae-54e2b3fdafde'),
           'time': '2020 年 3 月 3 日 03:03:03',
           'type': '电力预测'},
          {'amount': 10,
           'id': UUID('d7e21775-23e4-326f-91ae-54e2b3fdafde'),
           'time': '2020 年 4 月 4 日 04:04:04',
           'type': '电力预测'},
          {'amount': 10,
           'id': UUID('d7e21775-23e4-326f-91ae-54e2b3fdafde'),
           'time': '2020 年 5 月 5 日 05:05:05',
           'type': '电力预测'},
          {'amount': 10,
           'id': UUID('d7e21775-23e4-326f-91ae-54e2b3fdafde'),
           'time': '2020 年 6 月 6 日 06:06:06',
           'type': '电力预测'},
          {'amount': 10,
           'id': UUID('d7e21775-23e4-326f-91ae-54e2b3fdafde'),
           'time': '2020 年 7 月 7 日 07:07:07',
           'type': '电力预测'},
          {'amount': 10,
           'id': UUID('d7e21775-23e4-326f-91ae-54e2b3fdafde'),
           'time': '2020 年 8 月 8 日 08:08:08',
           'type': '电力预测'},
          {'amount': 10,
           'id': UUID('d7e21775-23e4-326f-91ae-54e2b3fdafde'),
           'time': '2020 年 9 月 9 日 09:09:09',
           'type': '电力预测'},
          {'amount': 10,
           'id': UUID('d7e21775-23e4-326f-91ae-54e2b3fdafde'),
           'time': '2020 年 10 月 10 日 10:10:10',
           'type': '电力预测'},
          {'amount': 10,
           'id': UUID('d7e21775-23e4-326f-91ae-54e2b3fdafde'),
           'time': '2020 年 11 月 11 日 11:11:11',
           'type': '电力预测'},
          {'amount': 10,
           'id': UUID('d7e21775-23e4-326f-91ae-54e2b3fdafde'),
           'time': '2020 年 12 月 12 日 12:12:12',
           'type': '电力预测'}],
 'msg': 'success'}
