FORMAT: 1A

+ Response 200 (application/json)

# [/api/predict/history/detail]
## HistoryPredictionDetail [GET]

{'code': 200,
 'data': {'amount': 42,
          'data': [{'x': 42, 'y': 84, 'y2nd': 88},
                   {'x': 42, 'y': 84, 'y2nd': 88},
                   {'x': 42, 'y': 84, 'y2nd': 88},
                   {'x': 42, 'y': 84, 'y2nd': 88},
                   {'x': 42, 'y': 84, 'y2nd': 88},
                   {'x': 42, 'y': 84, 'y2nd': 88},
                   {'x': 42, 'y': 84, 'y2nd': 88},
                   {'x': 42, 'y': 84, 'y2nd': 88},
                   {'x': 42, 'y': 84, 'y2nd': 88},
                   {'x': 42, 'y': 84, 'y2nd': 88},
                   {'x': 42, 'y': 84, 'y2nd': 88},
                   {'x': 42, 'y': 84, 'y2nd': 88},
                   {'x': 42, 'y': 84, 'y2nd': 88},
                   {'x': 42, 'y': 84, 'y2nd': 88},
                   {'x': 42, 'y': 84, 'y2nd': 88},
                   {'x': 42, 'y': 84, 'y2nd': 88},
                   {'x': 42, 'y': 84, 'y2nd': 88},
                   {'x': 42, 'y': 84, 'y2nd': 88},
                   {'x': 42, 'y': 84, 'y2nd': 88},
                   {'x': 42, 'y': 84, 'y2nd': 88}],
          'dimension': 2,
          'time': '2020 年 4 月 20 日 14:07:33',
          'type': '电力预测'},
 'msg': 'success'}
