FORMAT: 1A

+ Response 200 (application/json)

# [/api/predict/industry/single]
## IndustrySinglePredict [POST]

{'code': 200,
 'data': {'graphData': [{'xName': '1', 'yValue': 314},
                        {'xName': '2', 'yValue': 689},
                        {'xName': '3', 'yValue': 879},
                        {'xName': '4', 'yValue': 111},
                        {'xName': '5', 'yValue': 31},
                        {'xName': '6', 'yValue': 741},
                        {'xName': '7', 'yValue': 909},
                        {'xName': '8', 'yValue': 33},
                        {'xName': '9', 'yValue': 633},
                        {'xName': '10', 'yValue': 774},
                        {'xName': '11', 'yValue': 600},
                        {'xName': '12', 'yValue': 29},
                        {'xName': '13', 'yValue': 368},
                        {'xName': '14', 'yValue': 176},
                        {'xName': '15', 'yValue': 64},
                        {'xName': '16', 'yValue': 462},
                        {'xName': '17', 'yValue': 445}],
          'tableOneData': [{'index': '评价指标 1',
                            'mape': 0.8926022825394764,
                            'r2': 0.06992057740056168,
                            'rmse': 0.9507523786313208},
                           {'index': '评价指标 2',
                            'mape': 0.6896893000532085,
                            'r2': 0.2276091239937872,
                            'rmse': 0.49175993084797065},
                           {'index': '评价指标 3',
                            'mape': 0.7965805832171287,
                            'r2': 0.8940907952083398,
                            'rmse': 0.5312550883475733},
                           {'index': '评价指标 4',
                            'mape': 0.6926051722420216,
                            'r2': 0.24081661087449302,
                            'rmse': 0.673898444726925},
                           {'index': '评价指标 5',
                            'mape': 0.7090171104798954,
                            'r2': 0.09651028529864247,
                            'rmse': 0.5560420709281125},
                           {'index': '评价指标 6',
                            'mape': 0.612814116529096,
                            'r2': 0.2210904102920601,
                            'rmse': 0.193928905049929},
                           {'index': '评价指标 7',
                            'mape': 0.8851265522266023,
                            'r2': 0.5858588875816413,
                            'rmse': 0.5433893613972958},
                           {'index': '评价指标 8',
                            'mape': 0.7761550755602967,
                            'r2': 0.782326396535342,
                            'rmse': 0.45336590327503024},
                           {'index': '评价指标 9',
                            'mape': 0.8801316742849489,
                            'r2': 0.8379295538989323,
                            'rmse': 0.2594945906248942},
                           {'index': '评价指标 10',
                            'mape': 0.29262138783853886,
                            'r2': 0.1380091548850435,
                            'rmse': 0.6312175753697993},
                           {'index': '评价指标 11',
                            'mape': 0.13743205074511278,
                            'r2': 0.09360058293379903,
                            'rmse': 0.6865197433667775},
                           {'index': '评价指标 12',
                            'mape': 0.9560608691897529,
                            'r2': 0.9751455042787334,
                            'rmse': 0.9912846839313028},
                           {'index': '评价指标 13',
                            'mape': 0.6036695430397667,
                            'r2': 0.3523079035085174,
                            'rmse': 0.56556882819094},
                           {'index': '评价指标 14',
                            'mape': 0.29290116483989737,
                            'r2': 0.9850169912961695,
                            'rmse': 0.7386415693624772},
                           {'index': '评价指标 15',
                            'mape': 0.12324457210574735,
                            'r2': 0.2522882982468916,
                            'rmse': 0.4679390651692398},
                           {'index': '评价指标 16',
                            'mape': 0.19077518429260176,
                            'r2': 0.4262555762154724,
                            'rmse': 0.6760506502883221},
                           {'index': '评价指标 17',
                            'mape': 0.39602086404568015,
                            'r2': 0.9826491601443567,
                            'rmse': 0.8979361404281652}],
          'tableTwoData': [{'predict': 256.32483967442585, 'year': 2010},
                           {'predict': 148.22031736057377, 'year': 2011},
                           {'predict': 168.23243962845265, 'year': 2012},
                           {'predict': 159.29478575834776, 'year': 2013},
                           {'predict': 177.64769982541418, 'year': 2014},
                           {'predict': 389.570096533453, 'year': 2015},
                           {'predict': 295.68924158876905, 'year': 2016},
                           {'predict': 237.0552377142612, 'year': 2017},
                           {'predict': 191.75557595018032, 'year': 2018},
                           {'predict': 98.60582317746079, 'year': 2019},
                           {'predict': 125.18816794606494, 'year': 2020},
                           {'predict': 146.6791734982702, 'year': 2021},
                           {'predict': 313.70216263142635, 'year': 2022},
                           {'predict': 497.801194801874, 'year': 2023},
                           {'predict': 194.5031151108347, 'year': 2024},
                           {'predict': 406.1456920224501, 'year': 2025},
                           {'predict': 392.38848759903425, 'year': 2026}]},
 'msg': 'success'}
