FORMAT: 1A

+ Response 200 (application/json)

# [/api/predict/industry/single]
## IndustrySinglePredict [POST]

{'code': 200,
 'data': {'graphData': [{'xName': '1', 'yValue': 478},
                        {'xName': '2', 'yValue': 671},
                        {'xName': '3', 'yValue': 25},
                        {'xName': '4', 'yValue': 574},
                        {'xName': '5', 'yValue': 901},
                        {'xName': '6', 'yValue': 950},
                        {'xName': '7', 'yValue': 169},
                        {'xName': '8', 'yValue': 307},
                        {'xName': '9', 'yValue': 898},
                        {'xName': '10', 'yValue': 501},
                        {'xName': '11', 'yValue': 594},
                        {'xName': '12', 'yValue': 416},
                        {'xName': '13', 'yValue': 886},
                        {'xName': '14', 'yValue': 443},
                        {'xName': '15', 'yValue': 71},
                        {'xName': '16', 'yValue': 556},
                        {'xName': '17', 'yValue': 994}],
          'tableOneData': [{'index': '评价指标 1',
                            'mape': 0.7542754248646752,
                            'r2': 0.5812079341570244,
                            'rmse': 0.8546273953966527},
                           {'index': '评价指标 2',
                            'mape': 0.5916290624708431,
                            'r2': 0.9604556361518649,
                            'rmse': 0.2799209755695178},
                           {'index': '评价指标 3',
                            'mape': 0.43546472816952686,
                            'r2': 0.5071851908558781,
                            'rmse': 0.7105472555963588},
                           {'index': '评价指标 4',
                            'mape': 0.9851226807678909,
                            'r2': 0.2038239098567629,
                            'rmse': 0.4056753083234407},
                           {'index': '评价指标 5',
                            'mape': 0.45692826006756504,
                            'r2': 0.8946447226949611,
                            'rmse': 0.293968841248747},
                           {'index': '评价指标 6',
                            'mape': 0.4240958736495152,
                            'r2': 0.4115932717239079,
                            'rmse': 0.6257474921203726},
                           {'index': '评价指标 7',
                            'mape': 0.876102460241133,
                            'r2': 0.9631409653564333,
                            'rmse': 0.47516274746328335},
                           {'index': '评价指标 8',
                            'mape': 0.7288435639565876,
                            'r2': 0.3725596353908692,
                            'rmse': 0.7617006893045379},
                           {'index': '评价指标 9',
                            'mape': 0.07861925509640866,
                            'r2': 0.30774227131888043,
                            'rmse': 0.5721562755419941},
                           {'index': '评价指标 10',
                            'mape': 0.39351008086846273,
                            'r2': 0.09600628229149855,
                            'rmse': 0.8289147646938728},
                           {'index': '评价指标 11',
                            'mape': 0.5284726654350262,
                            'r2': 0.6891962917682679,
                            'rmse': 0.5895483583501484},
                           {'index': '评价指标 12',
                            'mape': 0.0937629700963607,
                            'r2': 0.34210876990629935,
                            'rmse': 0.008171287963545604},
                           {'index': '评价指标 13',
                            'mape': 0.526641234120685,
                            'r2': 0.15725165320877088,
                            'rmse': 0.035406310389052065},
                           {'index': '评价指标 14',
                            'mape': 0.8744973576359871,
                            'r2': 0.6876825632376652,
                            'rmse': 0.6821902373928317},
                           {'index': '评价指标 15',
                            'mape': 0.5768524146262135,
                            'r2': 0.04741192430745256,
                            'rmse': 0.8520798331684258},
                           {'index': '评价指标 16',
                            'mape': 0.36082449766430225,
                            'r2': 0.684790502949083,
                            'rmse': 0.21849273074314213},
                           {'index': '评价指标 17',
                            'mape': 0.7694280798111116,
                            'r2': 0.5639377672121922,
                            'rmse': 0.61889867306489}],
          'tableTwoData': [{'predict': 131.2914154411568, 'year': 2010},
                           {'predict': 351.3151444290034, 'year': 2011},
                           {'predict': 294.23543105466547, 'year': 2012},
                           {'predict': 224.04987532891448, 'year': 2013},
                           {'predict': 394.88417183084556, 'year': 2014},
                           {'predict': 280.416526092481, 'year': 2015},
                           {'predict': 37.88658974384587, 'year': 2016},
                           {'predict': 176.3729103402344, 'year': 2017},
                           {'predict': 76.71794662991901, 'year': 2018},
                           {'predict': 20.815608597186078, 'year': 2019},
                           {'predict': 134.84310825606335, 'year': 2020},
                           {'predict': 116.48939649941636, 'year': 2021},
                           {'predict': 2.2915255921773987, 'year': 2022},
                           {'predict': 326.7200466005681, 'year': 2023},
                           {'predict': 342.8417826229391, 'year': 2024},
                           {'predict': 138.4424711233446, 'year': 2025},
                           {'predict': 363.37492724009195, 'year': 2026}]},
 'msg': 'success'}
