FORMAT: 1A

+ Response 200 (application/json)

# [/api/predict/industry/single]
## IndustrySinglePredict [POST]

{'code': 200,
 'data': {'graphData': [{'xName': '1', 'yValue': 142},
                        {'xName': '2', 'yValue': 91},
                        {'xName': '3', 'yValue': 347},
                        {'xName': '4', 'yValue': 131},
                        {'xName': '5', 'yValue': 919},
                        {'xName': '6', 'yValue': 235},
                        {'xName': '7', 'yValue': 297},
                        {'xName': '8', 'yValue': 144},
                        {'xName': '9', 'yValue': 409},
                        {'xName': '10', 'yValue': 139},
                        {'xName': '11', 'yValue': 746},
                        {'xName': '12', 'yValue': 581},
                        {'xName': '13', 'yValue': 203},
                        {'xName': '14', 'yValue': 410},
                        {'xName': '15', 'yValue': 288},
                        {'xName': '16', 'yValue': 250},
                        {'xName': '17', 'yValue': 7}],
          'tableOneData': [{'index': '评价指标 1',
                            'mape': 0.14545763597506767,
                            'r2': 0.12715089600902774,
                            'rmse': 0.5064483093083513},
                           {'index': '评价指标 2',
                            'mape': 0.22555788948125421,
                            'r2': 0.06619850884441636,
                            'rmse': 0.28528984187189},
                           {'index': '评价指标 3',
                            'mape': 0.5556812605548042,
                            'r2': 0.40075970074471945,
                            'rmse': 0.15418931388652568},
                           {'index': '评价指标 4',
                            'mape': 0.05669400083001408,
                            'r2': 0.5221691974910166,
                            'rmse': 0.9230780199167051},
                           {'index': '评价指标 5',
                            'mape': 0.2904349072990974,
                            'r2': 0.3259703626629089,
                            'rmse': 0.5805828730574966},
                           {'index': '评价指标 6',
                            'mape': 0.26830922792290546,
                            'r2': 0.6002864772770241,
                            'rmse': 0.952781926716123},
                           {'index': '评价指标 7',
                            'mape': 0.9674778805189062,
                            'r2': 0.4126820337537249,
                            'rmse': 0.9813766588478977},
                           {'index': '评价指标 8',
                            'mape': 0.03715680253107856,
                            'r2': 0.9357767185033854,
                            'rmse': 0.32428246967685115},
                           {'index': '评价指标 9',
                            'mape': 0.03458848713567608,
                            'r2': 0.9174030154523398,
                            'rmse': 0.034347986478572734},
                           {'index': '评价指标 10',
                            'mape': 0.46404125924981077,
                            'r2': 0.12942581233603578,
                            'rmse': 0.7457149295648572},
                           {'index': '评价指标 11',
                            'mape': 0.9670074339059458,
                            'r2': 0.31270363977018245,
                            'rmse': 0.3828226992014113},
                           {'index': '评价指标 12',
                            'mape': 0.01292525855640736,
                            'r2': 0.20471955389155805,
                            'rmse': 0.9341875944024599},
                           {'index': '评价指标 13',
                            'mape': 0.3305336188730612,
                            'r2': 0.5495382788233331,
                            'rmse': 0.49007252055542583},
                           {'index': '评价指标 14',
                            'mape': 0.21955090155174062,
                            'r2': 0.20659820009941232,
                            'rmse': 0.5657080729935302},
                           {'index': '评价指标 15',
                            'mape': 0.5290195703600833,
                            'r2': 0.3666239103198259,
                            'rmse': 0.868058014899728},
                           {'index': '评价指标 16',
                            'mape': 0.6917734478089066,
                            'r2': 0.10055475294945626,
                            'rmse': 0.9621009605972436},
                           {'index': '评价指标 17',
                            'mape': 0.1921115550485667,
                            'r2': 0.25326799259538624,
                            'rmse': 0.8528786177010024}],
          'tableTwoData': [{'predict': 150.40783609952487, 'year': 2010},
                           {'predict': 256.14747876912065, 'year': 2011},
                           {'predict': 81.5347317774484, 'year': 2012},
                           {'predict': 169.81994503528097, 'year': 2013},
                           {'predict': 46.39441529327235, 'year': 2014},
                           {'predict': 208.5785790197464, 'year': 2015},
                           {'predict': 364.8948120134627, 'year': 2016},
                           {'predict': 187.98867957802676, 'year': 2017},
                           {'predict': 135.3075452967489, 'year': 2018},
                           {'predict': 110.10148123391566, 'year': 2019},
                           {'predict': 125.51076909985184, 'year': 2020},
                           {'predict': 406.89262814599033, 'year': 2021},
                           {'predict': 258.205776239715, 'year': 2022},
                           {'predict': 344.02593398685514, 'year': 2023},
                           {'predict': 115.56872975865804, 'year': 2024},
                           {'predict': 1.4458636236442495, 'year': 2025},
                           {'predict': 222.5589707871879, 'year': 2026}]},
 'msg': 'success'}
