FORMAT: 1A

+ Response 200 (application/json)

# [/api/predict/industry/mix]
## IndustryMixPredict [POST]

{'code': 200,
 'data': {'graphData': [{'xName': '1', 'yValue': 649},
                        {'xName': '2', 'yValue': 27},
                        {'xName': '3', 'yValue': 373},
                        {'xName': '4', 'yValue': 806},
                        {'xName': '5', 'yValue': 364},
                        {'xName': '6', 'yValue': 547},
                        {'xName': '7', 'yValue': 430},
                        {'xName': '8', 'yValue': 441},
                        {'xName': '9', 'yValue': 433},
                        {'xName': '10', 'yValue': 188},
                        {'xName': '11', 'yValue': 679},
                        {'xName': '12', 'yValue': 915},
                        {'xName': '13', 'yValue': 881},
                        {'xName': '14', 'yValue': 642},
                        {'xName': '15', 'yValue': 668},
                        {'xName': '16', 'yValue': 251},
                        {'xName': '17', 'yValue': 690}],
          'tableOneData': [{'index': '评价指标 1',
                            'mape': 0.14986772009759897,
                            'r2': 0.10008194434633644,
                            'rmse': 0.7184638921610632},
                           {'index': '评价指标 2',
                            'mape': 0.9673025645256366,
                            'r2': 0.217099955766326,
                            'rmse': 0.7924270078825958},
                           {'index': '评价指标 3',
                            'mape': 0.340557161096506,
                            'r2': 0.919189488624861,
                            'rmse': 0.18857495436773852},
                           {'index': '评价指标 4',
                            'mape': 0.269706498829571,
                            'r2': 0.713184937146613,
                            'rmse': 0.4256728014679535},
                           {'index': '评价指标 5',
                            'mape': 0.37605202420113404,
                            'r2': 0.38681755638171333,
                            'rmse': 0.07988090663381031},
                           {'index': '评价指标 6',
                            'mape': 0.42531358138438724,
                            'r2': 0.01586050084288282,
                            'rmse': 0.8451889302846863},
                           {'index': '评价指标 7',
                            'mape': 0.4957870961800328,
                            'r2': 0.19152671564442592,
                            'rmse': 0.04096877680433353},
                           {'index': '评价指标 8',
                            'mape': 0.752477009395521,
                            'r2': 0.38806044293646125,
                            'rmse': 0.3054816718695107},
                           {'index': '评价指标 9',
                            'mape': 0.3140542872912564,
                            'r2': 0.15049659327259457,
                            'rmse': 0.6409824890823247},
                           {'index': '评价指标 10',
                            'mape': 0.8266816080368846,
                            'r2': 0.06139104474523904,
                            'rmse': 0.7408264818889082},
                           {'index': '评价指标 11',
                            'mape': 0.6638094543619625,
                            'r2': 0.7104861180744059,
                            'rmse': 0.3574208778148976},
                           {'index': '评价指标 12',
                            'mape': 0.8427229794025541,
                            'r2': 0.7210432421698002,
                            'rmse': 0.8257458584231164},
                           {'index': '评价指标 13',
                            'mape': 0.2863838800655707,
                            'r2': 0.4948284671038994,
                            'rmse': 0.023210958348355626},
                           {'index': '评价指标 14',
                            'mape': 0.4888220971055708,
                            'r2': 0.11399817709465043,
                            'rmse': 0.24992775543019963},
                           {'index': '评价指标 15',
                            'mape': 0.7946191440778329,
                            'r2': 0.4094834665432159,
                            'rmse': 0.2942827931341653},
                           {'index': '评价指标 16',
                            'mape': 0.23838256663163193,
                            'r2': 0.7162177956079422,
                            'rmse': 0.2841949222326863},
                           {'index': '评价指标 17',
                            'mape': 0.3715709878531013,
                            'r2': 0.08528196630289175,
                            'rmse': 0.2428220621158198}],
          'tableTwoData': [{'predict': 128.85671312952576, 'year': 2010},
                           {'predict': 90.27476515463268, 'year': 2011},
                           {'predict': 23.226148534577014, 'year': 2012},
                           {'predict': 427.4394998579082, 'year': 2013},
                           {'predict': 46.74371191102204, 'year': 2014},
                           {'predict': 158.15740597106984, 'year': 2015},
                           {'predict': 212.66343031291768, 'year': 2016},
                           {'predict': 263.742809882357, 'year': 2017},
                           {'predict': 305.79282553985405, 'year': 2018},
                           {'predict': 93.14958526207882, 'year': 2019},
                           {'predict': 350.6006012197336, 'year': 2020},
                           {'predict': 7.21908305519697, 'year': 2021},
                           {'predict': 144.5074674647458, 'year': 2022},
                           {'predict': 2.8316185379058174, 'year': 2023},
                           {'predict': 141.0754383588336, 'year': 2024},
                           {'predict': 109.03926082075864, 'year': 2025},
                           {'predict': 170.0271938137824, 'year': 2026}]},
 'msg': 'success'}
