FORMAT: 1A

+ Response 200 (application/json)

# [/api/predict/industry/mix]
## IndustryMixPredict [POST]

{'code': 200,
 'data': {'graphData': [{'xName': '1', 'yValue': 297},
                        {'xName': '2', 'yValue': 392},
                        {'xName': '3', 'yValue': 321},
                        {'xName': '4', 'yValue': 809},
                        {'xName': '5', 'yValue': 259},
                        {'xName': '6', 'yValue': 921},
                        {'xName': '7', 'yValue': 624},
                        {'xName': '8', 'yValue': 582},
                        {'xName': '9', 'yValue': 591},
                        {'xName': '10', 'yValue': 986},
                        {'xName': '11', 'yValue': 986},
                        {'xName': '12', 'yValue': 33},
                        {'xName': '13', 'yValue': 163},
                        {'xName': '14', 'yValue': 320},
                        {'xName': '15', 'yValue': 347},
                        {'xName': '16', 'yValue': 278},
                        {'xName': '17', 'yValue': 600}],
          'tableOneData': [{'index': '评价指标 1',
                            'mape': 0.7538980012327052,
                            'r2': 0.4589525096637491,
                            'rmse': 0.10972399897293506},
                           {'index': '评价指标 2',
                            'mape': 0.03734378624825796,
                            'r2': 0.38012191288028807,
                            'rmse': 0.7225422907763495},
                           {'index': '评价指标 3',
                            'mape': 0.8411840261776995,
                            'r2': 0.02597416154112009,
                            'rmse': 0.6081797008495512},
                           {'index': '评价指标 4',
                            'mape': 0.22613902257910223,
                            'r2': 0.1103684155564163,
                            'rmse': 0.29795968896200675},
                           {'index': '评价指标 5',
                            'mape': 0.4064248714467188,
                            'r2': 0.800932596123278,
                            'rmse': 0.7332459683795663},
                           {'index': '评价指标 6',
                            'mape': 0.18234658149590133,
                            'r2': 0.7186202671735699,
                            'rmse': 0.08609968203438056},
                           {'index': '评价指标 7',
                            'mape': 0.45748979852380245,
                            'r2': 0.5519731774618954,
                            'rmse': 0.8737190244146548},
                           {'index': '评价指标 8',
                            'mape': 0.46740582366220373,
                            'r2': 0.8206961400885728,
                            'rmse': 0.2943346399080451},
                           {'index': '评价指标 9',
                            'mape': 0.07488241656082473,
                            'r2': 0.02955568181983248,
                            'rmse': 0.7390693567976858},
                           {'index': '评价指标 10',
                            'mape': 0.8295570294710387,
                            'r2': 0.3362714614407166,
                            'rmse': 0.7097408039159496},
                           {'index': '评价指标 11',
                            'mape': 0.016100521208681884,
                            'r2': 0.7017036565099649,
                            'rmse': 0.04090779041665915},
                           {'index': '评价指标 12',
                            'mape': 0.1869018729745019,
                            'r2': 0.6350369489706976,
                            'rmse': 0.21227469481309458},
                           {'index': '评价指标 13',
                            'mape': 0.2656508514647282,
                            'r2': 0.9898237133698922,
                            'rmse': 0.6891780202274108},
                           {'index': '评价指标 14',
                            'mape': 0.9178294369966374,
                            'r2': 0.22688276341315516,
                            'rmse': 0.18686313670930432},
                           {'index': '评价指标 15',
                            'mape': 0.048492391724647366,
                            'r2': 0.691639780318714,
                            'rmse': 0.25157606413470857},
                           {'index': '评价指标 16',
                            'mape': 0.0675615539458404,
                            'r2': 0.5675554881629553,
                            'rmse': 0.4627521608349401},
                           {'index': '评价指标 17',
                            'mape': 0.7513802502290184,
                            'r2': 0.8565662683244374,
                            'rmse': 0.8000590459861886}],
          'tableTwoData': [{'predict': 101.19442002747952, 'year': 2010},
                           {'predict': 47.08628733697467, 'year': 2011},
                           {'predict': 237.84764893037885, 'year': 2012},
                           {'predict': 206.0581814550869, 'year': 2013},
                           {'predict': 152.32865563692297, 'year': 2014},
                           {'predict': 263.9564450506036, 'year': 2015},
                           {'predict': 304.4096373770042, 'year': 2016},
                           {'predict': 367.14577017837814, 'year': 2017},
                           {'predict': 0.8292530098154942, 'year': 2018},
                           {'predict': 278.4199916077775, 'year': 2019},
                           {'predict': 368.5849226351737, 'year': 2020},
                           {'predict': 241.27279978426733, 'year': 2021},
                           {'predict': 223.2783794029247, 'year': 2022},
                           {'predict': 41.4501350615948, 'year': 2023},
                           {'predict': 327.051329855953, 'year': 2024},
                           {'predict': 35.877421353563335, 'year': 2025},
                           {'predict': 57.09438232443181, 'year': 2026}]},
 'msg': 'success'}
