FORMAT: 1A

+ Response 200 (application/json)

# [/api/predict/industry/mix]
## IndustryMixPredict [POST]

{'code': 200,
 'data': {'graphData': [{'xName': '1', 'yValue': 267},
                        {'xName': '2', 'yValue': 628},
                        {'xName': '3', 'yValue': 23},
                        {'xName': '4', 'yValue': 579},
                        {'xName': '5', 'yValue': 315},
                        {'xName': '6', 'yValue': 315},
                        {'xName': '7', 'yValue': 688},
                        {'xName': '8', 'yValue': 369},
                        {'xName': '9', 'yValue': 142},
                        {'xName': '10', 'yValue': 8},
                        {'xName': '11', 'yValue': 834},
                        {'xName': '12', 'yValue': 920},
                        {'xName': '13', 'yValue': 129},
                        {'xName': '14', 'yValue': 312},
                        {'xName': '15', 'yValue': 971},
                        {'xName': '16', 'yValue': 37},
                        {'xName': '17', 'yValue': 668}],
          'tableOneData': [{'index': '评价指标 1',
                            'mape': 0.0033416087109922055,
                            'r2': 0.209237457296383,
                            'rmse': 0.9446698320825258},
                           {'index': '评价指标 2',
                            'mape': 0.3167617510272239,
                            'r2': 0.01514628409900709,
                            'rmse': 0.4018427279149709},
                           {'index': '评价指标 3',
                            'mape': 0.1283643311575423,
                            'r2': 0.10239057153181397,
                            'rmse': 0.11499494730903337},
                           {'index': '评价指标 4',
                            'mape': 0.7957710791856435,
                            'r2': 0.4334318432755596,
                            'rmse': 0.5069331436273121},
                           {'index': '评价指标 5',
                            'mape': 0.9264678877387599,
                            'r2': 0.6788203376590619,
                            'rmse': 0.07184036547050454},
                           {'index': '评价指标 6',
                            'mape': 0.41315542266496397,
                            'r2': 0.37320264548569515,
                            'rmse': 0.5893322721320589},
                           {'index': '评价指标 7',
                            'mape': 0.4207114243682212,
                            'r2': 0.8474635463085785,
                            'rmse': 0.6515916903304311},
                           {'index': '评价指标 8',
                            'mape': 0.5793662272722994,
                            'r2': 0.6704608686320385,
                            'rmse': 0.21023708610930358},
                           {'index': '评价指标 9',
                            'mape': 0.04305688205659608,
                            'r2': 0.5313084180136095,
                            'rmse': 0.2960482403024648},
                           {'index': '评价指标 10',
                            'mape': 0.4057839582494812,
                            'r2': 0.3893431837389061,
                            'rmse': 0.38488054049236675},
                           {'index': '评价指标 11',
                            'mape': 0.7732407923884889,
                            'r2': 0.7355277330664495,
                            'rmse': 0.7980715175681602},
                           {'index': '评价指标 12',
                            'mape': 0.30005510099829524,
                            'r2': 0.6982446115123205,
                            'rmse': 0.023040703494366932},
                           {'index': '评价指标 13',
                            'mape': 0.02494505722772944,
                            'r2': 0.718273172825591,
                            'rmse': 0.353613968265606},
                           {'index': '评价指标 14',
                            'mape': 0.03651546705327835,
                            'r2': 0.2050553492866094,
                            'rmse': 0.9003092685916331},
                           {'index': '评价指标 15',
                            'mape': 0.8150211642906539,
                            'r2': 0.8549582745952252,
                            'rmse': 0.12740551948701084},
                           {'index': '评价指标 16',
                            'mape': 0.3296601215921072,
                            'r2': 0.5536103513640767,
                            'rmse': 0.6316496231166064},
                           {'index': '评价指标 17',
                            'mape': 0.569865835561908,
                            'r2': 0.6999369263876751,
                            'rmse': 0.3611156569056766}],
          'tableTwoData': [{'predict': 219.96639044710741, 'year': 2010},
                           {'predict': 242.3476856654832, 'year': 2011},
                           {'predict': 158.56235672313602, 'year': 2012},
                           {'predict': 326.7600607546181, 'year': 2013},
                           {'predict': 226.9100325197865, 'year': 2014},
                           {'predict': 381.76210884336274, 'year': 2015},
                           {'predict': 103.65988517778098, 'year': 2016},
                           {'predict': 55.47404646526155, 'year': 2017},
                           {'predict': 456.1794384193269, 'year': 2018},
                           {'predict': 47.14024223244476, 'year': 2019},
                           {'predict': 119.02767353785548, 'year': 2020},
                           {'predict': 143.11753802443505, 'year': 2021},
                           {'predict': 318.51829346192955, 'year': 2022},
                           {'predict': 44.88068448223698, 'year': 2023},
                           {'predict': 163.49122761468396, 'year': 2024},
                           {'predict': 196.665900876458, 'year': 2025},
                           {'predict': 142.66756168858342, 'year': 2026}]},
 'msg': 'success'}
