FORMAT: 1A

+ Response 200 (application/json)

# [/api/method/industry/query]

## IndustrialMethodQuery [GET]

{'code': 200,
 'data': ['基于ARIMA季节分解的行业电量预测',
          '基于EEMD的行业用电量预测',
          '基于主成分因子的行业用电量预测',
          '基于随机森林的行业用电量预测',
          '基于神经网络的行业用电量预测'],
 'msg': 'success'}
