FORMAT: 1A

+ Response 200 (application/json)

# [/api/payload/predict/interp]
## InterpolatingPayloadPredict [POST]

{'code': 200,
 'data': [{'actualPayload': 589406, 'predictPayload': 804009, 'time': '13:25'},
          {'actualPayload': 775871, 'predictPayload': 86533, 'time': '10:44'},
          {'actualPayload': 212240, 'predictPayload': 773978, 'time': '10:50'},
          {'actualPayload': 342800, 'predictPayload': 966196, 'time': '12:41'},
          {'actualPayload': 834200, 'predictPayload': 85032, 'time': '18:47'},
          {'actualPayload': 698074, 'predictPayload': 57318, 'time': '15:44'},
          {'actualPayload': 173509, 'predictPayload': 682353, 'time': '19:15'},
          {'actualPayload': 769580, 'predictPayload': 442366, 'time': '10:42'},
          {'actualPayload': 531825, 'predictPayload': 93395, 'time': '12:16'},
          {'actualPayload': 486161, 'predictPayload': 429214, 'time': '15:28'},
          {'actualPayload': 655376, 'predictPayload': 868006, 'time': '18:11'},
          {'actualPayload': 830593, 'predictPayload': 79075, 'time': '13:39'}],
 'msg': 'success'}
