FORMAT: 1A

+ Response 200 (application/json)

# [/api/payload/predict/interp]
## InterpolatingPayloadPredict [POST]

{'code': 200,
 'data': [{'actualPayload': 327136, 'predictPayload': 183301, 'time': '10:49'},
          {'actualPayload': 62005, 'predictPayload': 291004, 'time': '15:24'},
          {'actualPayload': 28552, 'predictPayload': 998834, 'time': '10:36'},
          {'actualPayload': 884925, 'predictPayload': 558239, 'time': '19:19'},
          {'actualPayload': 573034, 'predictPayload': 57138, 'time': '14:45'},
          {'actualPayload': 779654, 'predictPayload': 888915, 'time': '18:13'},
          {'actualPayload': 123500, 'predictPayload': 980794, 'time': '17:25'},
          {'actualPayload': 253402, 'predictPayload': 794037, 'time': '16:24'},
          {'actualPayload': 602520, 'predictPayload': 488698, 'time': '14:40'},
          {'actualPayload': 798187, 'predictPayload': 893433, 'time': '12:48'},
          {'actualPayload': 726127, 'predictPayload': 907259, 'time': '19:28'},
          {'actualPayload': 745709, 'predictPayload': 276412, 'time': '17:10'}],
 'msg': 'success'}
