FORMAT: 1A

+ Response 200 (application/json)

# [/api/params/predict/interp]

## InterpolatingPayloadPredictionParameters [GET]

{'code': 200,
 'data': {'beginYear': 2012,
          'dailyAmount': 28888,
          'endYear': 2022,
          'maxPayload': 14444,
          'season': 3},
 'msg': 'success'}
