FORMAT: 1A

+ Response 200 (application/json)

# [/api/payload/predict/interp]
## InterpolatingPayloadPredict [POST]

{'code': 200,
 'data': [{'actualPayload': 372413, 'predictPayload': 494858, 'time': '18:28'},
          {'actualPayload': 383940, 'predictPayload': 241898, 'time': '20:30'},
          {'actualPayload': 631792, 'predictPayload': 742510, 'time': '16:44'},
          {'actualPayload': 115499, 'predictPayload': 694476, 'time': '20:27'},
          {'actualPayload': 16395, 'predictPayload': 655717, 'time': '17:29'},
          {'actualPayload': 846298, 'predictPayload': 502387, 'time': '14:32'},
          {'actualPayload': 85847, 'predictPayload': 644940, 'time': '19:12'},
          {'actualPayload': 79868, 'predictPayload': 379591, 'time': '19:31'},
          {'actualPayload': 774633, 'predictPayload': 664607, 'time': '10:41'},
          {'actualPayload': 128367, 'predictPayload': 258435, 'time': '14:34'},
          {'actualPayload': 963541, 'predictPayload': 217361, 'time': '14:20'},
          {'actualPayload': 276480, 'predictPayload': 956084, 'time': '14:31'}],
 'msg': 'success'}
