FORMAT: 1A

+ Response 200 (application/json)

# [/api/recent]
## LoadRecent [GET]

{'code': 200,
 'data': [{'name': '预测软件页面初步设计方案',
           'url': 'https://th.bing.com/th/id/OIP.iLmhNJwXEioFCxt2cisBGgHaES?w=274&h=180&c=7&o=5&dpr=2&pid=1.7'},
          {'name': '问题回复',
           'url': 'https://th.bing.com/th/id/OIP.LE7rdh-q39ceZfXtus1ifAHaE7?w=270&h=180&c=7&o=5&dpr=2&pid=1.7'}],
 'msg': 'success'}
