FORMAT: 1A

+ Response 200 (application/json)

# [/api/params/predict/dynamic/region]
## LongTermPredictionParameters [GET]

{'code': 200,
 'data': {'beginYear': 1993,
          'endYear': 2013,
          'historyBeginYear': 2012,
          'historyEndYear': 2022,
          'method': '行业',
          'parameters': ['1', '2', '...'],
          'region': '地域'},
 'msg': 'success'}
