FORMAT: 1A

+ Response 200 (application/json)

# [/api/params/predict/dynamic/region]
## LongTermPredictionParameters [GET]

{'code': 200,
 'data': {'beginYear': 0,
          'endYear': 0,
          'historyBeginYear': 0,
          'historyEndYear': 0,
          'method': '',
          'parameters': ['1', '2', Ellipsis],
          'region': ''},
 'msg': 'success'}
