FORMAT: 1A

+ Response 200 (application/json)

# [/api/mining/results]
## MiningResults [GET]

{'code': 200,
 'data': [{'plan': '某个挖掘计划', 'results': ['阳光', '空气', '水']},
          {'plan': '另一个挖掘计划', 'results': ['光风', '霁月']},
          {'plan': '最后一个挖掘计划', 'results': ['阴雨', '晦冥']}],
 'msg': 'success'}
