FORMAT: 1A

+ Response 200 (application/json)

# [/api/params/predict/mix]
## MixPredictionParameters [GET]

{'code': 200,
 'data': {'beginYear': 2012,
          'endYear': 2022,
          'historyBeginYear': 2012,
          'historyEndYear': 2066,
          'industry': '工业',
          'region': '地域',
          'selectedMethods': ['methodA', 'methodB', '...']},
 'msg': 'success'}
