FORMAT: 1A

+ Response 200 (application/json)

# [/api/params/predict/mix]
## MixPredictionParameters [GET]

{'code': 200,
 'data': {'beginYear': 0,
          'endYear': 0,
          'historyBeginYear': 0,
          'historyEndYear': 0,
          'industry': '',
          'region': '',
          'selectedMethods': ['methodA', 'methodB', Ellipsis]},
 'msg': 'success'}
