FORMAT: 1A

+ Response 200 (application/json)

# [/api/payload/traits/monthly]
## MonthlyPayloadTraits [GET]

{'code': 200,
 'data': [{'month': '2020 年 1 月',
           'monthAverageDailyPayload': 204,
           'monthAverageDailyPayloadRate': 297.35850831395226,
           'monthAveragePayloadRate': 256.94540293689863,
           'monthImbaRate': 165.4822274797837,
           'monthMaxPeekValleyDiff': 91.24304911209913,
           'monthMinPayloadRate': 354.7457043092638},
          {'month': '2020 年 2 月',
           'monthAverageDailyPayload': 742,
           'monthAverageDailyPayloadRate': 80.5284468874392,
           'monthAveragePayloadRate': 236.5313707659497,
           'monthImbaRate': 315.38788202089444,
           'monthMaxPeekValleyDiff': 129.2500352666703,
           'monthMinPayloadRate': 271.6928399192186},
          {'month': '2020 年 3 月',
           'monthAverageDailyPayload': 719,
           'monthAverageDailyPayloadRate': 267.4192062849074,
           'monthAveragePayloadRate': 404.815684281664,
           'monthImbaRate': 145.46343619141723,
           'monthMaxPeekValleyDiff': 186.21150089730648,
           'monthMinPayloadRate': 450.34611154044126},
          {'month': '2020 年 4 月',
           'monthAverageDailyPayload': 516,
           'monthAverageDailyPayloadRate': 129.61287075278477,
           'monthAveragePayloadRate': 6.451106969466047,
           'monthImbaRate': 392.58278187204314,
           'monthMaxPeekValleyDiff': 373.5695854637912,
           'monthMinPayloadRate': 492.16388311199364},
          {'month': '2020 年 5 月',
           'monthAverageDailyPayload': 660,
           'monthAverageDailyPayloadRate': 141.01684859812391,
           'monthAveragePayloadRate': 280.3527222750497,
           'monthImbaRate': 361.14046988454277,
           'monthMaxPeekValleyDiff': 173.82700687067015,
           'monthMinPayloadRate': 238.3914846532385},
          {'month': '2020 年 6 月',
           'monthAverageDailyPayload': 156,
           'monthAverageDailyPayloadRate': 478.64908430106607,
           'monthAveragePayloadRate': 372.9568990008821,
           'monthImbaRate': 181.208864036816,
           'monthMaxPeekValleyDiff': 425.89057927753424,
           'monthMinPayloadRate': 381.2570085204031},
          {'month': '2020 年 7 月',
           'monthAverageDailyPayload': 115,
           'monthAverageDailyPayloadRate': 290.566009605372,
           'monthAveragePayloadRate': 429.3532109192218,
           'monthImbaRate': 49.67063375520453,
           'monthMaxPeekValleyDiff': 142.9247138268021,
           'monthMinPayloadRate': 225.43083481843723},
          {'month': '2020 年 8 月',
           'monthAverageDailyPayload': 536,
           'monthAverageDailyPayloadRate': 392.1815093725239,
           'monthAveragePayloadRate': 120.5843509756065,
           'monthImbaRate': 282.844330339729,
           'monthMaxPeekValleyDiff': 130.4588761812861,
           'monthMinPayloadRate': 365.7487269084318},
          {'month': '2020 年 9 月',
           'monthAverageDailyPayload': 248,
           'monthAverageDailyPayloadRate': 110.51164000031221,
           'monthAveragePayloadRate': 340.14802117829674,
           'monthImbaRate': 419.18102116619,
           'monthMaxPeekValleyDiff': 455.5687781127447,
           'monthMinPayloadRate': 48.204454107257654},
          {'month': '2020 年 10 月',
           'monthAverageDailyPayload': 326,
           'monthAverageDailyPayloadRate': 122.14896499117422,
           'monthAveragePayloadRate': 13.781042039886449,
           'monthImbaRate': 287.9596035952265,
           'monthMaxPeekValleyDiff': 402.79376430354404,
           'monthMinPayloadRate': 97.55807369554559},
          {'month': '2020 年 11 月',
           'monthAverageDailyPayload': 651,
           'monthAverageDailyPayloadRate': 171.82771019231757,
           'monthAveragePayloadRate': 125.92518152539833,
           'monthImbaRate': 253.48679404182346,
           'monthMaxPeekValleyDiff': 352.2326186349302,
           'monthMinPayloadRate': 394.4215775720425},
          {'month': '2020 年 12 月',
           'monthAverageDailyPayload': 818,
           'monthAverageDailyPayloadRate': 323.33837183537327,
           'monthAveragePayloadRate': 122.25951293383552,
           'monthImbaRate': 244.77964933314001,
           'monthMaxPeekValleyDiff': 243.78051460759553,
           'monthMinPayloadRate': 468.3459604268019}],
 'msg': 'success'}
