FORMAT: 1A

+ Response 200 (application/json)

# [/api/payload/traits/monthly]
## MonthlyPayloadTraits [GET]

{'code': 200,
 'data': [{'month': '2020 年 1 月',
           'monthAverageDailyPayload': 956,
           'monthAverageDailyPayloadRate': 219.38236763811835,
           'monthAveragePayloadRate': 232.78556629738594,
           'monthImbaRate': 245.2667646716808,
           'monthMaxPeekValleyDiff': 348.7745660495438,
           'monthMinPayloadRate': 42.402183619553945},
          {'month': '2020 年 2 月',
           'monthAverageDailyPayload': 33,
           'monthAverageDailyPayloadRate': 211.5902022495304,
           'monthAveragePayloadRate': 73.54491451909057,
           'monthImbaRate': 283.2933603197212,
           'monthMaxPeekValleyDiff': 77.13965241509457,
           'monthMinPayloadRate': 299.1857775006942},
          {'month': '2020 年 3 月',
           'monthAverageDailyPayload': 121,
           'monthAverageDailyPayloadRate': 299.8792218456678,
           'monthAveragePayloadRate': 345.62457009721976,
           'monthImbaRate': 56.25264882028075,
           'monthMaxPeekValleyDiff': 356.74029483356054,
           'monthMinPayloadRate': 145.06309496045338},
          {'month': '2020 年 4 月',
           'monthAverageDailyPayload': 361,
           'monthAverageDailyPayloadRate': 133.71510519657537,
           'monthAveragePayloadRate': 390.26083740960865,
           'monthImbaRate': 22.650889834629815,
           'monthMaxPeekValleyDiff': 474.45600807719757,
           'monthMinPayloadRate': 449.8991768479694},
          {'month': '2020 年 5 月',
           'monthAverageDailyPayload': 153,
           'monthAverageDailyPayloadRate': 55.484415496481645,
           'monthAveragePayloadRate': 401.1069458989631,
           'monthImbaRate': 264.1089247103971,
           'monthMaxPeekValleyDiff': 218.81468953378686,
           'monthMinPayloadRate': 244.73116758187706},
          {'month': '2020 年 6 月',
           'monthAverageDailyPayload': 405,
           'monthAverageDailyPayloadRate': 9.7461159168869,
           'monthAveragePayloadRate': 466.0477057541797,
           'monthImbaRate': 343.4455338561538,
           'monthMaxPeekValleyDiff': 388.2259939432444,
           'monthMinPayloadRate': 206.43043836676583},
          {'month': '2020 年 7 月',
           'monthAverageDailyPayload': 813,
           'monthAverageDailyPayloadRate': 87.17488836271336,
           'monthAveragePayloadRate': 12.124994369366371,
           'monthImbaRate': 360.37651235255834,
           'monthMaxPeekValleyDiff': 202.23875456808238,
           'monthMinPayloadRate': 425.871901599049},
          {'month': '2020 年 8 月',
           'monthAverageDailyPayload': 931,
           'monthAverageDailyPayloadRate': 317.56929806152624,
           'monthAveragePayloadRate': 222.90188146112223,
           'monthImbaRate': 53.008456748911804,
           'monthMaxPeekValleyDiff': 368.119691384899,
           'monthMinPayloadRate': 482.5769463941575},
          {'month': '2020 年 9 月',
           'monthAverageDailyPayload': 252,
           'monthAverageDailyPayloadRate': 397.6079446821995,
           'monthAveragePayloadRate': 279.83454373650676,
           'monthImbaRate': 102.71749236188116,
           'monthMaxPeekValleyDiff': 442.78948058184596,
           'monthMinPayloadRate': 476.58867631492535},
          {'month': '2020 年 10 月',
           'monthAverageDailyPayload': 590,
           'monthAverageDailyPayloadRate': 169.08595480921724,
           'monthAveragePayloadRate': 421.08743942262055,
           'monthImbaRate': 352.4109003655005,
           'monthMaxPeekValleyDiff': 158.20987569980645,
           'monthMinPayloadRate': 346.08030237257003},
          {'month': '2020 年 11 月',
           'monthAverageDailyPayload': 948,
           'monthAverageDailyPayloadRate': 235.48549362149635,
           'monthAveragePayloadRate': 46.863706505868684,
           'monthImbaRate': 70.1223539809993,
           'monthMaxPeekValleyDiff': 404.4457165262707,
           'monthMinPayloadRate': 409.76387335352103},
          {'month': '2020 年 12 月',
           'monthAverageDailyPayload': 458,
           'monthAverageDailyPayloadRate': 447.6899224611962,
           'monthAveragePayloadRate': 164.5348749194734,
           'monthImbaRate': 154.0810782540337,
           'monthMaxPeekValleyDiff': 314.2537548562958,
           'monthMinPayloadRate': 381.31845287449244}],
 'msg': 'success'}
