FORMAT: 1A

+ Response 200 (application/json)

# [/api/predict/payload]
## PayloadDensityPredict [POST]

{'code': 200,
 'data': {'graphData': [{'xName': '1', 'yValue': 706},
                        {'xName': '2', 'yValue': 447},
                        {'xName': '3', 'yValue': 397},
                        {'xName': '4', 'yValue': 374},
                        {'xName': '5', 'yValue': 754},
                        {'xName': '6', 'yValue': 375},
                        {'xName': '7', 'yValue': 952},
                        {'xName': '8', 'yValue': 486},
                        {'xName': '9', 'yValue': 802},
                        {'xName': '10', 'yValue': 393},
                        {'xName': '11', 'yValue': 131},
                        {'xName': '12', 'yValue': 316},
                        {'xName': '13', 'yValue': 852},
                        {'xName': '14', 'yValue': 63},
                        {'xName': '15', 'yValue': 437},
                        {'xName': '16', 'yValue': 777},
                        {'xName': '17', 'yValue': 164}],
          'tableOneData': [{'index': '评价指标 1',
                            'mape': 0.7602355337162028,
                            'r2': 0.28667097965649047,
                            'rmse': 0.9017125909259639},
                           {'index': '评价指标 2',
                            'mape': 0.34010063537106117,
                            'r2': 0.08544479629949964,
                            'rmse': 0.5133469801815628},
                           {'index': '评价指标 3',
                            'mape': 0.9189758489184613,
                            'r2': 0.8631896571821419,
                            'rmse': 0.8111393964734934},
                           {'index': '评价指标 4',
                            'mape': 0.9864896400167098,
                            'r2': 0.3502011264257737,
                            'rmse': 0.10676765718211323},
                           {'index': '评价指标 5',
                            'mape': 0.3099860711693313,
                            'r2': 0.7447744778777552,
                            'rmse': 0.11135537044835997},
                           {'index': '评价指标 6',
                            'mape': 0.1174302338636849,
                            'r2': 0.7742152474504536,
                            'rmse': 0.19144454351310536},
                           {'index': '评价指标 7',
                            'mape': 0.132833572416454,
                            'r2': 0.8109490242049406,
                            'rmse': 0.3893319729288126},
                           {'index': '评价指标 8',
                            'mape': 0.39435927147800065,
                            'r2': 0.15588881829942047,
                            'rmse': 0.8347830801912145},
                           {'index': '评价指标 9',
                            'mape': 0.22702974614704774,
                            'r2': 0.5804237565295757,
                            'rmse': 0.3132565935280318},
                           {'index': '评价指标 10',
                            'mape': 0.6890066083505235,
                            'r2': 0.7563069629533306,
                            'rmse': 0.14440781833327354},
                           {'index': '评价指标 11',
                            'mape': 0.2622242686016032,
                            'r2': 0.7886361192392992,
                            'rmse': 0.9921281385908061},
                           {'index': '评价指标 12',
                            'mape': 0.8555159502102476,
                            'r2': 0.2981461357463019,
                            'rmse': 0.7133788309815754},
                           {'index': '评价指标 13',
                            'mape': 0.4685625494025125,
                            'r2': 0.968589049472686,
                            'rmse': 0.23180038195498154},
                           {'index': '评价指标 14',
                            'mape': 0.4204502395866416,
                            'r2': 0.5707094293706189,
                            'rmse': 0.1820870514970191},
                           {'index': '评价指标 15',
                            'mape': 0.09111661620372846,
                            'r2': 0.6648024869572949,
                            'rmse': 0.7193618835217562},
                           {'index': '评价指标 16',
                            'mape': 0.7124350295182229,
                            'r2': 0.42512219716792476,
                            'rmse': 0.7444839638940928},
                           {'index': '评价指标 17',
                            'mape': 0.2475358034636368,
                            'r2': 0.7508126322155824,
                            'rmse': 0.8154015380047245}],
          'tableTwoData': [{'predict': 264.71575863420463, 'year': 2010},
                           {'predict': 199.824513842008, 'year': 2011},
                           {'predict': 301.74429334798003, 'year': 2012},
                           {'predict': 296.7014714881761, 'year': 2013},
                           {'predict': 116.50591019147103, 'year': 2014},
                           {'predict': 255.42025388880288, 'year': 2015},
                           {'predict': 228.37075804258592, 'year': 2016},
                           {'predict': 213.66048966299843, 'year': 2017},
                           {'predict': 69.8422506976398, 'year': 2018},
                           {'predict': 256.02781048597586, 'year': 2019},
                           {'predict': 122.4457227229791, 'year': 2020},
                           {'predict': 229.62732220529566, 'year': 2021},
                           {'predict': 224.05088727714138, 'year': 2022},
                           {'predict': 456.8885069309608, 'year': 2023},
                           {'predict': 48.447930918701886, 'year': 2024},
                           {'predict': 348.3878384112902, 'year': 2025},
                           {'predict': 288.65484779523945, 'year': 2026}]},
 'msg': 'success'}
