FORMAT: 1A

+ Response 200 (application/json)

# [/api/predict/payload]
## PayloadDensityPredict [POST]

{'code': 200,
 'data': {'graphData': [{'xName': '1', 'yValue': 196},
                        {'xName': '2', 'yValue': 693},
                        {'xName': '3', 'yValue': 539},
                        {'xName': '4', 'yValue': 219},
                        {'xName': '5', 'yValue': 986},
                        {'xName': '6', 'yValue': 325},
                        {'xName': '7', 'yValue': 728},
                        {'xName': '8', 'yValue': 226},
                        {'xName': '9', 'yValue': 563},
                        {'xName': '10', 'yValue': 398},
                        {'xName': '11', 'yValue': 455},
                        {'xName': '12', 'yValue': 913},
                        {'xName': '13', 'yValue': 266},
                        {'xName': '14', 'yValue': 644},
                        {'xName': '15', 'yValue': 512},
                        {'xName': '16', 'yValue': 300},
                        {'xName': '17', 'yValue': 489}],
          'tableOneData': [{'index': '评价指标 1',
                            'mape': 0.7184910232161098,
                            'r2': 0.09146922808228597,
                            'rmse': 0.19161075826394902},
                           {'index': '评价指标 2',
                            'mape': 0.8331292967232554,
                            'r2': 0.8122670485169952,
                            'rmse': 0.3335453864801724},
                           {'index': '评价指标 3',
                            'mape': 0.8625113642706523,
                            'r2': 0.5442945828521517,
                            'rmse': 0.657510437296919},
                           {'index': '评价指标 4',
                            'mape': 0.5824322485812792,
                            'r2': 0.7185363448244696,
                            'rmse': 0.15625960278637852},
                           {'index': '评价指标 5',
                            'mape': 0.8034415652396049,
                            'r2': 0.44366305239078174,
                            'rmse': 0.4934047032982759},
                           {'index': '评价指标 6',
                            'mape': 0.6190464435998554,
                            'r2': 0.8818466483662307,
                            'rmse': 0.8804302437342181},
                           {'index': '评价指标 7',
                            'mape': 0.1934212438867553,
                            'r2': 0.19211476953670004,
                            'rmse': 0.7605622847029714},
                           {'index': '评价指标 8',
                            'mape': 0.8882485174441134,
                            'r2': 0.5618211162051804,
                            'rmse': 0.3729559141230062},
                           {'index': '评价指标 9',
                            'mape': 0.05201006610976888,
                            'r2': 0.29495692590731304,
                            'rmse': 0.701474845670779},
                           {'index': '评价指标 10',
                            'mape': 0.07443177953694113,
                            'r2': 0.42421012375926337,
                            'rmse': 0.6461939102627371},
                           {'index': '评价指标 11',
                            'mape': 0.321050597603629,
                            'r2': 0.4028854110705278,
                            'rmse': 0.9489659189670424},
                           {'index': '评价指标 12',
                            'mape': 0.36968197891380317,
                            'r2': 0.2680134112690129,
                            'rmse': 0.9646995230621497},
                           {'index': '评价指标 13',
                            'mape': 0.5646681460040296,
                            'r2': 0.7095156395209097,
                            'rmse': 0.8833005203781423},
                           {'index': '评价指标 14',
                            'mape': 0.20756924586036118,
                            'r2': 0.05908524901670864,
                            'rmse': 0.741598383379407},
                           {'index': '评价指标 15',
                            'mape': 0.5661641878275314,
                            'r2': 0.47770604306285325,
                            'rmse': 0.6062185724585951},
                           {'index': '评价指标 16',
                            'mape': 0.7787591588318337,
                            'r2': 0.5346234611197024,
                            'rmse': 0.7660637088326624},
                           {'index': '评价指标 17',
                            'mape': 0.972787161409248,
                            'r2': 0.48467233229391316,
                            'rmse': 0.4844083845668711}],
          'tableTwoData': [{'predict': 122.9062390970006, 'year': 2010},
                           {'predict': 69.27513175436468, 'year': 2011},
                           {'predict': 433.21885005339516, 'year': 2012},
                           {'predict': 10.754505812625766, 'year': 2013},
                           {'predict': 411.9922296887631, 'year': 2014},
                           {'predict': 107.34358627589575, 'year': 2015},
                           {'predict': 277.0954328714623, 'year': 2016},
                           {'predict': 313.1718726063999, 'year': 2017},
                           {'predict': 207.59571640401998, 'year': 2018},
                           {'predict': 129.59894926669185, 'year': 2019},
                           {'predict': 267.2233649555435, 'year': 2020},
                           {'predict': 353.35713307359026, 'year': 2021},
                           {'predict': 311.54913959261347, 'year': 2022},
                           {'predict': 147.09448579460687, 'year': 2023},
                           {'predict': 416.42066465180665, 'year': 2024},
                           {'predict': 260.9791094796045, 'year': 2025},
                           {'predict': 102.60891602503992, 'year': 2026}]},
 'msg': 'success'}
