FORMAT: 1A

+ Response 200 (application/json)

# [/api/predict/payload]
## PayloadDensityPredict [POST]

{'code': 200,
 'data': {'graphData': [{'xName': '1', 'yValue': 379},
                        {'xName': '2', 'yValue': 961},
                        {'xName': '3', 'yValue': 548},
                        {'xName': '4', 'yValue': 224},
                        {'xName': '5', 'yValue': 665},
                        {'xName': '6', 'yValue': 258},
                        {'xName': '7', 'yValue': 393},
                        {'xName': '8', 'yValue': 875},
                        {'xName': '9', 'yValue': 893},
                        {'xName': '10', 'yValue': 973},
                        {'xName': '11', 'yValue': 576},
                        {'xName': '12', 'yValue': 318},
                        {'xName': '13', 'yValue': 855},
                        {'xName': '14', 'yValue': 7},
                        {'xName': '15', 'yValue': 264},
                        {'xName': '16', 'yValue': 88},
                        {'xName': '17', 'yValue': 765}],
          'tableOneData': [{'index': '评价指标 1',
                            'mape': 0.31142958411354293,
                            'r2': 0.014977523122222669,
                            'rmse': 0.010134158390530557},
                           {'index': '评价指标 2',
                            'mape': 0.7097920637619818,
                            'r2': 0.44362213311705934,
                            'rmse': 0.81181388827554},
                           {'index': '评价指标 3',
                            'mape': 0.07620216446309402,
                            'r2': 0.44784057010366907,
                            'rmse': 0.1744225629034758},
                           {'index': '评价指标 4',
                            'mape': 0.521210128153413,
                            'r2': 0.3448943652567237,
                            'rmse': 0.9609698760586988},
                           {'index': '评价指标 5',
                            'mape': 0.05036728526268641,
                            'r2': 0.17756358084243995,
                            'rmse': 0.008182850927686003},
                           {'index': '评价指标 6',
                            'mape': 0.4425263896934759,
                            'r2': 0.8573576893725848,
                            'rmse': 0.7086234297662503},
                           {'index': '评价指标 7',
                            'mape': 0.49349147981718877,
                            'r2': 0.38839011136521606,
                            'rmse': 0.39495808707528457},
                           {'index': '评价指标 8',
                            'mape': 0.03274664276721506,
                            'r2': 0.9977960404625646,
                            'rmse': 0.015040405030921411},
                           {'index': '评价指标 9',
                            'mape': 0.9052548138107973,
                            'r2': 0.5137902380540401,
                            'rmse': 0.45136541815104125},
                           {'index': '评价指标 10',
                            'mape': 0.8545106586846256,
                            'r2': 0.14400478230015445,
                            'rmse': 0.725892514808941},
                           {'index': '评价指标 11',
                            'mape': 0.20800565142868344,
                            'r2': 0.9047115837918781,
                            'rmse': 0.8473206802547052},
                           {'index': '评价指标 12',
                            'mape': 0.7517561165091721,
                            'r2': 0.7948064399871944,
                            'rmse': 0.321865322222043},
                           {'index': '评价指标 13',
                            'mape': 0.34453034877648336,
                            'r2': 0.09179327257779746,
                            'rmse': 0.212515060946313},
                           {'index': '评价指标 14',
                            'mape': 0.1699639004278578,
                            'r2': 0.43022209076409845,
                            'rmse': 0.29059166201740316},
                           {'index': '评价指标 15',
                            'mape': 0.343902844326586,
                            'r2': 0.3738186761664194,
                            'rmse': 0.09742134121790624},
                           {'index': '评价指标 16',
                            'mape': 0.21476377531542534,
                            'r2': 0.3476445605267854,
                            'rmse': 0.8701899318763985},
                           {'index': '评价指标 17',
                            'mape': 0.9156210510868316,
                            'r2': 0.6617628870497906,
                            'rmse': 0.6124646526446746}],
          'tableTwoData': [{'predict': 282.88832487426384, 'year': 2010},
                           {'predict': 44.80341696485568, 'year': 2011},
                           {'predict': 297.59695785979346, 'year': 2012},
                           {'predict': 42.43506224028989, 'year': 2013},
                           {'predict': 185.0097201932011, 'year': 2014},
                           {'predict': 225.6587060280529, 'year': 2015},
                           {'predict': 255.59117916905853, 'year': 2016},
                           {'predict': 309.92877095132343, 'year': 2017},
                           {'predict': 293.31984179094417, 'year': 2018},
                           {'predict': 96.67059841924612, 'year': 2019},
                           {'predict': 124.90388039521629, 'year': 2020},
                           {'predict': 252.59692321599923, 'year': 2021},
                           {'predict': 119.65180085069997, 'year': 2022},
                           {'predict': 459.47708636873125, 'year': 2023},
                           {'predict': 95.04168002864164, 'year': 2024},
                           {'predict': 159.0907831973583, 'year': 2025},
                           {'predict': 95.37806866373788, 'year': 2026}]},
 'msg': 'success'}
