FORMAT: 1A

+ Response 200 (application/json)

# [/api/db/query]

## PerformQuery [POST]

{'code': 200,
 'data': [{'key': '2021-1-8', 'value': '陈瑞球'},
          {'key': '2021-1-7', 'value': '杨咏曼'},
          {'key': '2021-1-5', 'value': '蔡翠菊'},
          {'key': '2021-1-3', 'value': '包玉刚'}],
 'msg': 'success'}
