FORMAT: 1A

+ Response 200 (application/json)

# [/api/predict/provmuni]

## ProvincialAndMunicipalPredict [POST]

{'code': 200,
 'data': {'tableFourData': [{'predictAfter': 287.3127312,
                             'predictBefore': 287.3127312,
                             'region': '某个地方',
                             'year': 2010},
                            {'predictAfter': 287.3127312,
                             'predictBefore': 287.3127312,
                             'region': '某个地方',
                             'year': 2011},
                            {'predictAfter': 287.3127312,
                             'predictBefore': 287.3127312,
                             'region': '某个地方',
                             'year': 2012},
                            {'predictAfter': 287.3127312,
                             'predictBefore': 287.3127312,
                             'region': '某个地方',
                             'year': 2013},
                            {'predictAfter': 287.3127312,
                             'predictBefore': 287.3127312,
                             'region': '某个地方',
                             'year': 2014},
                            {'predictAfter': 287.3127312,
                             'predictBefore': 287.3127312,
                             'region': '某个地方',
                             'year': 2015},
                            {'predictAfter': 287.3127312,
                             'predictBefore': 287.3127312,
                             'region': '某个地方',
                             'year': 2016},
                            {'predictAfter': 287.3127312,
                             'predictBefore': 287.3127312,
                             'region': '某个地方',
                             'year': 2017},
                            {'predictAfter': 287.3127312,
                             'predictBefore': 287.3127312,
                             'region': '某个地方',
                             'year': 2018},
                            {'predictAfter': 287.3127312,
                             'predictBefore': 287.3127312,
                             'region': '某个地方',
                             'year': 2019},
                            {'predictAfter': 287.3127312,
                             'predictBefore': 287.3127312,
                             'region': '某个地方',
                             'year': 2020},
                            {'predictAfter': 287.3127312,
                             'predictBefore': 287.3127312,
                             'region': '某个地方',
                             'year': 2021},
                            {'predictAfter': 287.3127312,
                             'predictBefore': 287.3127312,
                             'region': '某个地方',
                             'year': 2022},
                            {'predictAfter': 287.3127312,
                             'predictBefore': 287.3127312,
                             'region': '某个地方',
                             'year': 2023},
                            {'predictAfter': 287.3127312,
                             'predictBefore': 287.3127312,
                             'region': '某个地方',
                             'year': 2024},
                            {'predictAfter': 287.3127312,
                             'predictBefore': 287.3127312,
                             'region': '某个地方',
                             'year': 2025},
                            {'predictAfter': 287.3127312,
                             'predictBefore': 287.3127312,
                             'region': '某个地方',
                             'year': 2026}],
          'tableThreeData': [{'predictErrorAfter': 35.9140914,
                              'predictErrorBefore': 28.731273119999997,
                              'predictValueAfter': 287.3127312,
                              'predictValueBefore': 287.3127312,
                              'region': '某个地方',
                              'year': 2011},
                             {'predictErrorAfter': 35.9140914,
                              'predictErrorBefore': 28.731273119999997,
                              'predictValueAfter': 287.3127312,
                              'predictValueBefore': 287.3127312,
                              'region': '某个地方',
                              'year': 2012},
                             {'predictErrorAfter': 35.9140914,
                              'predictErrorBefore': 28.731273119999997,
                              'predictValueAfter': 287.3127312,
                              'predictValueBefore': 287.3127312,
                              'region': '某个地方',
                              'year': 2013},
                             {'predictErrorAfter': 35.9140914,
                              'predictErrorBefore': 28.731273119999997,
                              'predictValueAfter': 287.3127312,
                              'predictValueBefore': 287.3127312,
                              'region': '某个地方',
                              'year': 2014},
                             {'predictErrorAfter': 35.9140914,
                              'predictErrorBefore': 28.731273119999997,
                              'predictValueAfter': 287.3127312,
                              'predictValueBefore': 287.3127312,
                              'region': '某个地方',
                              'year': 2015},
                             {'predictErrorAfter': 35.9140914,
                              'predictErrorBefore': 28.731273119999997,
                              'predictValueAfter': 287.3127312,
                              'predictValueBefore': 287.3127312,
                              'region': '某个地方',
                              'year': 2016},
                             {'predictErrorAfter': 35.9140914,
                              'predictErrorBefore': 28.731273119999997,
                              'predictValueAfter': 287.3127312,
                              'predictValueBefore': 287.3127312,
                              'region': '某个地方',
                              'year': 2017},
                             {'predictErrorAfter': 35.9140914,
                              'predictErrorBefore': 28.731273119999997,
                              'predictValueAfter': 287.3127312,
                              'predictValueBefore': 287.3127312,
                              'region': '某个地方',
                              'year': 2018},
                             {'predictErrorAfter': 35.9140914,
                              'predictErrorBefore': 28.731273119999997,
                              'predictValueAfter': 287.3127312,
                              'predictValueBefore': 287.3127312,
                              'region': '某个地方',
                              'year': 2019},
                             {'predictErrorAfter': 35.9140914,
                              'predictErrorBefore': 28.731273119999997,
                              'predictValueAfter': 287.3127312,
                              'predictValueBefore': 287.3127312,
                              'region': '某个地方',
                              'year': 2020},
                             {'predictErrorAfter': 35.9140914,
                              'predictErrorBefore': 28.731273119999997,
                              'predictValueAfter': 287.3127312,
                              'predictValueBefore': 287.3127312,
                              'region': '某个地方',
                              'year': 2021},
                             {'predictErrorAfter': 35.9140914,
                              'predictErrorBefore': 28.731273119999997,
                              'predictValueAfter': 287.3127312,
                              'predictValueBefore': 287.3127312,
                              'region': '某个地方',
                              'year': 2022},
                             {'predictErrorAfter': 35.9140914,
                              'predictErrorBefore': 28.731273119999997,
                              'predictValueAfter': 287.3127312,
                              'predictValueBefore': 287.3127312,
                              'region': '某个地方',
                              'year': 2023},
                             {'predictErrorAfter': 35.9140914,
                              'predictErrorBefore': 28.731273119999997,
                              'predictValueAfter': 287.3127312,
                              'predictValueBefore': 287.3127312,
                              'region': '某个地方',
                              'year': 2024},
                             {'predictErrorAfter': 35.9140914,
                              'predictErrorBefore': 28.731273119999997,
                              'predictValueAfter': 287.3127312,
                              'predictValueBefore': 287.3127312,
                              'region': '某个地方',
                              'year': 2025},
                             {'predictErrorAfter': 35.9140914,
                              'predictErrorBefore': 28.731273119999997,
                              'predictValueAfter': 287.3127312,
                              'predictValueBefore': 287.3127312,
                              'region': '某个地方',
                              'year': 2026},
                             {'predictErrorAfter': 35.9140914,
                              'predictErrorBefore': 28.731273119999997,
                              'predictValueAfter': 287.3127312,
                              'predictValueBefore': 287.3127312,
                              'region': '某个地方',
                              'year': 2027}]},
 'msg': 'success'}
