FORMAT: 1A

+ Response 200 (application/json)

# [/api/predict/provmuni]
## ProvincialAndMunicipalPredict [POST]

{'code': 200,
 'data': {'tableFourData': [{'predictAfter': 268.0999789228591,
                             'predictBefore': 56.227207378956706,
                             'region': '某个地方',
                             'year': 2010},
                            {'predictAfter': 355.3883948756893,
                             'predictBefore': 420.9218028264085,
                             'region': '某个地方',
                             'year': 2011},
                            {'predictAfter': 130.69202584745597,
                             'predictBefore': 109.57819321646393,
                             'region': '某个地方',
                             'year': 2012},
                            {'predictAfter': 139.08205517991985,
                             'predictBefore': 138.1951965430984,
                             'region': '某个地方',
                             'year': 2013},
                            {'predictAfter': 266.92354772767476,
                             'predictBefore': 198.48505213030484,
                             'region': '某个地方',
                             'year': 2014},
                            {'predictAfter': 119.88888128990618,
                             'predictBefore': 25.076087533584676,
                             'region': '某个地方',
                             'year': 2015},
                            {'predictAfter': 125.00479868539547,
                             'predictBefore': 173.52158068093752,
                             'region': '某个地方',
                             'year': 2016},
                            {'predictAfter': 100.08107892191862,
                             'predictBefore': 178.5726958083088,
                             'region': '某个地方',
                             'year': 2017},
                            {'predictAfter': 217.04375641587214,
                             'predictBefore': 327.6775562353709,
                             'region': '某个地方',
                             'year': 2018},
                            {'predictAfter': 127.68250578709227,
                             'predictBefore': 61.57533048311128,
                             'region': '某个地方',
                             'year': 2019},
                            {'predictAfter': 107.28471851038155,
                             'predictBefore': 33.93497910986138,
                             'region': '某个地方',
                             'year': 2020},
                            {'predictAfter': 60.498399234007785,
                             'predictBefore': 135.88899277699775,
                             'region': '某个地方',
                             'year': 2021},
                            {'predictAfter': 223.53150667942128,
                             'predictBefore': 39.18685781445058,
                             'region': '某个地方',
                             'year': 2022},
                            {'predictAfter': 79.33713435912897,
                             'predictBefore': 251.43853826887892,
                             'region': '某个地方',
                             'year': 2023},
                            {'predictAfter': 299.8030161138815,
                             'predictBefore': 22.360287844403604,
                             'region': '某个地方',
                             'year': 2024},
                            {'predictAfter': 150.00257292475337,
                             'predictBefore': 239.15672984372407,
                             'region': '某个地方',
                             'year': 2025},
                            {'predictAfter': 181.01823725509036,
                             'predictBefore': 118.42647317143056,
                             'region': '某个地方',
                             'year': 2026}],
          'tableThreeData': [{'predictErrorAfter': 33.6323201018276,
                              'predictErrorBefore': 13.065738314157137,
                              'predictValueAfter': 84.03278106356939,
                              'predictValueBefore': 245.73406831079643,
                              'region': '某个地方',
                              'year': 2011},
                             {'predictErrorAfter': 29.093716229823222,
                              'predictErrorBefore': 35.49473006572346,
                              'predictValueAfter': 8.99966344554258,
                              'predictValueBefore': 246.941092033183,
                              'region': '某个地方',
                              'year': 2012},
                             {'predictErrorAfter': 7.038415854925708,
                              'predictErrorBefore': 22.06258067086752,
                              'predictValueAfter': 368.7707761653137,
                              'predictValueBefore': 142.321708762739,
                              'region': '某个地方',
                              'year': 2013},
                             {'predictErrorAfter': 43.74093698015419,
                              'predictErrorBefore': 9.929721623503397,
                              'predictValueAfter': 198.006166860286,
                              'predictValueBefore': 376.6994930096946,
                              'region': '某个地方',
                              'year': 2014},
                             {'predictErrorAfter': 0.7166555087299266,
                              'predictErrorBefore': 18.391496007452606,
                              'predictValueAfter': 345.0053084489296,
                              'predictValueBefore': 263.64076151262975,
                              'region': '某个地方',
                              'year': 2015},
                             {'predictErrorAfter': 19.200535372341434,
                              'predictErrorBefore': 8.257358590998281,
                              'predictValueAfter': 142.2763751329286,
                              'predictValueBefore': 462.2050945705331,
                              'region': '某个地方',
                              'year': 2016},
                             {'predictErrorAfter': 22.36101130469863,
                              'predictErrorBefore': 15.269527742962222,
                              'predictValueAfter': 375.68114332865537,
                              'predictValueBefore': 319.29341043310217,
                              'region': '某个地方',
                              'year': 2017},
                             {'predictErrorAfter': 33.10759852832608,
                              'predictErrorBefore': 12.372023631006444,
                              'predictValueAfter': 197.9675889595902,
                              'predictValueBefore': 82.54269164377322,
                              'region': '某个地方',
                              'year': 2018},
                             {'predictErrorAfter': 19.411295119657595,
                              'predictErrorBefore': 17.711315597248504,
                              'predictValueAfter': 292.00753080456053,
                              'predictValueBefore': 189.5605387679925,
                              'region': '某个地方',
                              'year': 2019},
                             {'predictErrorAfter': 24.62773915620676,
                              'predictErrorBefore': 16.519386554496577,
                              'predictValueAfter': 106.90591987894628,
                              'predictValueBefore': 254.36283110683024,
                              'region': '某个地方',
                              'year': 2020},
                             {'predictErrorAfter': 11.611214835084379,
                              'predictErrorBefore': 35.0434071209481,
                              'predictValueAfter': 19.002020428204112,
                              'predictValueBefore': 380.5646277728088,
                              'region': '某个地方',
                              'year': 2021},
                             {'predictErrorAfter': 13.81717456703182,
                              'predictErrorBefore': 19.755050716896605,
                              'predictValueAfter': 11.72897038960684,
                              'predictValueBefore': 339.3529069941811,
                              'region': '某个地方',
                              'year': 2022},
                             {'predictErrorAfter': 35.80705165482429,
                              'predictErrorBefore': 6.335399418982678,
                              'predictValueAfter': 342.76837550706455,
                              'predictValueBefore': 250.4867804798262,
                              'region': '某个地方',
                              'year': 2023},
                             {'predictErrorAfter': 18.316383662324508,
                              'predictErrorBefore': 18.533836552911758,
                              'predictValueAfter': 287.4417938358295,
                              'predictValueBefore': 223.959470501948,
                              'region': '某个地方',
                              'year': 2024},
                             {'predictErrorAfter': 31.503497741797894,
                              'predictErrorBefore': 0.6856222938056279,
                              'predictValueAfter': 460.1465676910422,
                              'predictValueBefore': 203.72202283253142,
                              'region': '某个地方',
                              'year': 2025},
                             {'predictErrorAfter': 11.330226002721194,
                              'predictErrorBefore': 1.6203137348354113,
                              'predictValueAfter': 318.1848571460232,
                              'predictValueBefore': 143.7367682280688,
                              'region': '某个地方',
                              'year': 2026},
                             {'predictErrorAfter': 31.76544138858031,
                              'predictErrorBefore': 7.0720365678540595,
                              'predictValueAfter': 133.7759632509311,
                              'predictValueBefore': 176.08153902424482,
                              'region': '某个地方',
                              'year': 2027}]},
 'msg': 'success'}
