FORMAT: 1A

+ Response 200 (application/json)

# [/api/predict/provmuni]
## ProvincialAndMunicipalPredict [POST]

{'code': 200,
 'data': {'tableFourData': [{'predictAfter': 257.6011840400934,
                             'predictBefore': 398.13033028380806,
                             'region': '某个地方',
                             'year': 2010},
                            {'predictAfter': 374.9194454618827,
                             'predictBefore': 146.41296546936232,
                             'region': '某个地方',
                             'year': 2011},
                            {'predictAfter': 71.19128049595578,
                             'predictBefore': 260.3356099577239,
                             'region': '某个地方',
                             'year': 2012},
                            {'predictAfter': 310.67667031985883,
                             'predictBefore': 323.5461346017068,
                             'region': '某个地方',
                             'year': 2013},
                            {'predictAfter': 52.19512537323431,
                             'predictBefore': 311.1033294814407,
                             'region': '某个地方',
                             'year': 2014},
                            {'predictAfter': 180.45646754387838,
                             'predictBefore': 275.65152811338055,
                             'region': '某个地方',
                             'year': 2015},
                            {'predictAfter': 245.53348072538765,
                             'predictBefore': 330.4933311841868,
                             'region': '某个地方',
                             'year': 2016},
                            {'predictAfter': 224.4660594555051,
                             'predictBefore': 1.9245993327684419,
                             'region': '某个地方',
                             'year': 2017},
                            {'predictAfter': 171.19414565707672,
                             'predictBefore': 272.7257721817074,
                             'region': '某个地方',
                             'year': 2018},
                            {'predictAfter': 229.23993597967447,
                             'predictBefore': 322.5260884437056,
                             'region': '某个地方',
                             'year': 2019},
                            {'predictAfter': 311.7491237696399,
                             'predictBefore': 254.32904507494868,
                             'region': '某个地方',
                             'year': 2020},
                            {'predictAfter': 135.45012895612257,
                             'predictBefore': 326.4020961877348,
                             'region': '某个地方',
                             'year': 2021},
                            {'predictAfter': 86.79342173776087,
                             'predictBefore': 188.408301387059,
                             'region': '某个地方',
                             'year': 2022},
                            {'predictAfter': 168.67175818140407,
                             'predictBefore': 239.75617456985995,
                             'region': '某个地方',
                             'year': 2023},
                            {'predictAfter': 318.48779578967515,
                             'predictBefore': 37.43692358111302,
                             'region': '某个地方',
                             'year': 2024},
                            {'predictAfter': 145.99571306532007,
                             'predictBefore': 376.9629513118871,
                             'region': '某个地方',
                             'year': 2025},
                            {'predictAfter': 263.4466078450082,
                             'predictBefore': 239.04878973174792,
                             'region': '某个地方',
                             'year': 2026}],
          'tableThreeData': [{'predictErrorAfter': 53.731171593480475,
                              'predictErrorBefore': 19.559685210670967,
                              'predictValueAfter': 143.02993274351647,
                              'predictValueBefore': 27.526165512292494,
                              'region': '某个地方',
                              'year': 2011},
                             {'predictErrorAfter': 18.539090374775217,
                              'predictErrorBefore': 16.40149155997611,
                              'predictValueAfter': 415.9029945580496,
                              'predictValueBefore': 456.5012041543088,
                              'region': '某个地方',
                              'year': 2012},
                             {'predictErrorAfter': 19.678519836465284,
                              'predictErrorBefore': 30.193233668732127,
                              'predictValueAfter': 264.53615553371964,
                              'predictValueBefore': 20.8706062516856,
                              'region': '某个地方',
                              'year': 2013},
                             {'predictErrorAfter': 4.917612121161564,
                              'predictErrorBefore': 6.932388877078688,
                              'predictValueAfter': 27.024166123753094,
                              'predictValueBefore': 86.95675114562376,
                              'region': '某个地方',
                              'year': 2014},
                             {'predictErrorAfter': 45.77326866255092,
                              'predictErrorBefore': 5.924563384421281,
                              'predictValueAfter': 155.1669156628247,
                              'predictValueBefore': 233.56373490106128,
                              'region': '某个地方',
                              'year': 2015},
                             {'predictErrorAfter': 29.189333186476304,
                              'predictErrorBefore': 40.42758906591092,
                              'predictValueAfter': 297.03275961111336,
                              'predictValueBefore': 299.0062818347731,
                              'region': '某个地方',
                              'year': 2016},
                             {'predictErrorAfter': 1.7989684458200346,
                              'predictErrorBefore': 22.50763952071251,
                              'predictValueAfter': 390.5991956304017,
                              'predictValueBefore': 283.25963115949605,
                              'region': '某个地方',
                              'year': 2017},
                             {'predictErrorAfter': 11.937619581252001,
                              'predictErrorBefore': 13.201439854348445,
                              'predictValueAfter': 174.94547520599878,
                              'predictValueBefore': 10.347808470453597,
                              'region': '某个地方',
                              'year': 2018},
                             {'predictErrorAfter': 27.84967765792912,
                              'predictErrorBefore': 11.980670149013756,
                              'predictValueAfter': 252.86421745206454,
                              'predictValueBefore': 459.7999278109361,
                              'region': '某个地方',
                              'year': 2019},
                             {'predictErrorAfter': 27.811332097115237,
                              'predictErrorBefore': 24.14513890194865,
                              'predictValueAfter': 0.021561451198809367,
                              'predictValueBefore': 487.7740060459552,
                              'region': '某个地方',
                              'year': 2020},
                             {'predictErrorAfter': 41.81152312815575,
                              'predictErrorBefore': 14.889750335970898,
                              'predictValueAfter': 296.97305169153555,
                              'predictValueBefore': 249.21380103294652,
                              'region': '某个地方',
                              'year': 2021},
                             {'predictErrorAfter': 50.40682369746554,
                              'predictErrorBefore': 23.098269151685212,
                              'predictValueAfter': 407.69982171760734,
                              'predictValueBefore': 176.9471678584131,
                              'region': '某个地方',
                              'year': 2022},
                             {'predictErrorAfter': 30.615675494083554,
                              'predictErrorBefore': 17.761653988322088,
                              'predictValueAfter': 97.71977503412255,
                              'predictValueBefore': 19.40352898686281,
                              'region': '某个地方',
                              'year': 2023},
                             {'predictErrorAfter': 42.12114261603415,
                              'predictErrorBefore': 27.692840940096417,
                              'predictValueAfter': 189.40123919680184,
                              'predictValueBefore': 402.11991231271924,
                              'region': '某个地方',
                              'year': 2024},
                             {'predictErrorAfter': 2.180206575381856,
                              'predictErrorBefore': 22.085040528809166,
                              'predictValueAfter': 127.27614256714665,
                              'predictValueBefore': 239.4683524006351,
                              'region': '某个地方',
                              'year': 2025},
                             {'predictErrorAfter': 2.109611851691464,
                              'predictErrorBefore': 37.46526942814188,
                              'predictValueAfter': 278.60243251775114,
                              'predictValueBefore': 62.280302802320776,
                              'region': '某个地方',
                              'year': 2026},
                             {'predictErrorAfter': 13.725154491743542,
                              'predictErrorBefore': 12.796443315592871,
                              'predictValueAfter': 418.51666993570694,
                              'predictValueBefore': 162.84037084131347,
                              'region': '某个地方',
                              'year': 2027}]},
 'msg': 'success'}
