FORMAT: 1A

+ Response 200 (application/json)

# [/api/predict/region/mix]
## RegionMixPredict [POST]

{'code': 200,
 'data': {'graphData': [{'xName': '1', 'yValue': 470},
                        {'xName': '2', 'yValue': 686},
                        {'xName': '3', 'yValue': 393},
                        {'xName': '4', 'yValue': 186},
                        {'xName': '5', 'yValue': 622},
                        {'xName': '6', 'yValue': 446},
                        {'xName': '7', 'yValue': 474},
                        {'xName': '8', 'yValue': 733},
                        {'xName': '9', 'yValue': 515},
                        {'xName': '10', 'yValue': 52},
                        {'xName': '11', 'yValue': 511},
                        {'xName': '12', 'yValue': 435},
                        {'xName': '13', 'yValue': 970},
                        {'xName': '14', 'yValue': 170},
                        {'xName': '15', 'yValue': 978},
                        {'xName': '16', 'yValue': 919},
                        {'xName': '17', 'yValue': 325}],
          'tableOneData': [{'index': '评价指标 1',
                            'mape': 0.8892915909221852,
                            'r2': 0.3487425859747708,
                            'rmse': 0.5929081556647747},
                           {'index': '评价指标 2',
                            'mape': 0.8468751135455944,
                            'r2': 0.014234230274449922,
                            'rmse': 0.34885564053949325},
                           {'index': '评价指标 3',
                            'mape': 0.6351179518905347,
                            'r2': 0.4996732745849357,
                            'rmse': 0.13058513659414506},
                           {'index': '评价指标 4',
                            'mape': 0.7924986244898868,
                            'r2': 0.14586528896425965,
                            'rmse': 0.3397435747880537},
                           {'index': '评价指标 5',
                            'mape': 0.46079563349987807,
                            'r2': 0.1266620798714425,
                            'rmse': 0.4629358524554499},
                           {'index': '评价指标 6',
                            'mape': 0.6498757306786128,
                            'r2': 0.137605039525319,
                            'rmse': 0.36512312367045563},
                           {'index': '评价指标 7',
                            'mape': 0.6608521801468739,
                            'r2': 0.7087657055770744,
                            'rmse': 0.08746222032916218},
                           {'index': '评价指标 8',
                            'mape': 0.571275081358203,
                            'r2': 0.9182488159554063,
                            'rmse': 0.5158717008928373},
                           {'index': '评价指标 9',
                            'mape': 0.8406644738468446,
                            'r2': 0.747948522904585,
                            'rmse': 0.9275820211899316},
                           {'index': '评价指标 10',
                            'mape': 0.10222957222477047,
                            'r2': 0.1635980070921801,
                            'rmse': 0.13183348584567278},
                           {'index': '评价指标 11',
                            'mape': 0.10510600081078691,
                            'r2': 0.25032524828117964,
                            'rmse': 0.7483682451290882},
                           {'index': '评价指标 12',
                            'mape': 0.17838864697073087,
                            'r2': 0.4371478787095906,
                            'rmse': 0.39499636882756517},
                           {'index': '评价指标 13',
                            'mape': 0.6453595155771766,
                            'r2': 0.28954387458188025,
                            'rmse': 0.9435601314147543},
                           {'index': '评价指标 14',
                            'mape': 0.29655038031856285,
                            'r2': 0.26425976673402063,
                            'rmse': 0.3130578320589342},
                           {'index': '评价指标 15',
                            'mape': 0.383708122125168,
                            'r2': 0.8707961002720026,
                            'rmse': 0.10943677122930195},
                           {'index': '评价指标 16',
                            'mape': 0.7107258103263964,
                            'r2': 0.2645370571475294,
                            'rmse': 0.9026795642242196},
                           {'index': '评价指标 17',
                            'mape': 0.9712824415174048,
                            'r2': 0.9573331014965746,
                            'rmse': 0.05921325040765901}],
          'tableTwoData': [{'predict': 173.31713398403915, 'year': 2010},
                           {'predict': 126.08748843958683, 'year': 2011},
                           {'predict': 338.81933308491523, 'year': 2012},
                           {'predict': 63.24398936511365, 'year': 2013},
                           {'predict': 234.10133300641462, 'year': 2014},
                           {'predict': 196.6281864490346, 'year': 2015},
                           {'predict': 374.62368093084217, 'year': 2016},
                           {'predict': 6.828478725700064, 'year': 2017},
                           {'predict': 267.19690615040776, 'year': 2018},
                           {'predict': 403.50150352035195, 'year': 2019},
                           {'predict': 204.02281214432566, 'year': 2020},
                           {'predict': 268.0621811620919, 'year': 2021},
                           {'predict': 417.4422724172591, 'year': 2022},
                           {'predict': 364.50387823305454, 'year': 2023},
                           {'predict': 173.17859881236313, 'year': 2024},
                           {'predict': 238.1659204951386, 'year': 2025},
                           {'predict': 23.490242683231102, 'year': 2026}]},
 'msg': 'success'}
