FORMAT: 1A

+ Response 200 (application/json)

# [/api/predict/region/single]
## RegionSinglePredict [POST]

{'code': 200,
 'data': {'graphData': [{'xName': '1', 'yValue': 418},
                        {'xName': '2', 'yValue': 540},
                        {'xName': '3', 'yValue': 124},
                        {'xName': '4', 'yValue': 924},
                        {'xName': '5', 'yValue': 82},
                        {'xName': '6', 'yValue': 361},
                        {'xName': '7', 'yValue': 769},
                        {'xName': '8', 'yValue': 762},
                        {'xName': '9', 'yValue': 674},
                        {'xName': '10', 'yValue': 351},
                        {'xName': '11', 'yValue': 397},
                        {'xName': '12', 'yValue': 954},
                        {'xName': '13', 'yValue': 888},
                        {'xName': '14', 'yValue': 311},
                        {'xName': '15', 'yValue': 284},
                        {'xName': '16', 'yValue': 870},
                        {'xName': '17', 'yValue': 223}],
          'tableOneData': [{'index': '评价指标 1',
                            'mape': 0.21916535329734976,
                            'r2': 0.7753058961697487,
                            'rmse': 0.7383988676125378},
                           {'index': '评价指标 2',
                            'mape': 0.7377144453523465,
                            'r2': 0.6328992200321234,
                            'rmse': 0.5249198972425154},
                           {'index': '评价指标 3',
                            'mape': 0.2609831287929749,
                            'r2': 0.18006242949456863,
                            'rmse': 0.8146352056299556},
                           {'index': '评价指标 4',
                            'mape': 0.5845400158708083,
                            'r2': 0.3166943084496363,
                            'rmse': 0.9138500552339734},
                           {'index': '评价指标 5',
                            'mape': 0.039805507494413694,
                            'r2': 0.9102914057656727,
                            'rmse': 0.40506229147797557},
                           {'index': '评价指标 6',
                            'mape': 0.3104097325816668,
                            'r2': 0.7692782104703806,
                            'rmse': 0.37704471275964646},
                           {'index': '评价指标 7',
                            'mape': 0.9791021414094779,
                            'r2': 0.9934831117481978,
                            'rmse': 0.9979982765433065},
                           {'index': '评价指标 8',
                            'mape': 0.39415460478047337,
                            'r2': 0.9990272256243553,
                            'rmse': 0.2390207117951122},
                           {'index': '评价指标 9',
                            'mape': 0.27535637263656654,
                            'r2': 0.6038400898705667,
                            'rmse': 0.9605984191040575},
                           {'index': '评价指标 10',
                            'mape': 0.6399896314076006,
                            'r2': 0.7491350345044968,
                            'rmse': 0.8440179938053126},
                           {'index': '评价指标 11',
                            'mape': 0.43587407838288617,
                            'r2': 0.6324818763160988,
                            'rmse': 0.8116844521320933},
                           {'index': '评价指标 12',
                            'mape': 0.25146761413909524,
                            'r2': 0.6921361160868994,
                            'rmse': 0.8749906697776719},
                           {'index': '评价指标 13',
                            'mape': 0.6771089082350948,
                            'r2': 0.1834916048931169,
                            'rmse': 0.5717798264090136},
                           {'index': '评价指标 14',
                            'mape': 0.9880616987189447,
                            'r2': 0.3415779247918713,
                            'rmse': 0.08909108463503257},
                           {'index': '评价指标 15',
                            'mape': 0.2672009652553011,
                            'r2': 0.11526128181374251,
                            'rmse': 0.9666577795276313},
                           {'index': '评价指标 16',
                            'mape': 0.40662047256110867,
                            'r2': 0.575044005622819,
                            'rmse': 0.5639537638095877},
                           {'index': '评价指标 17',
                            'mape': 0.2067407440271316,
                            'r2': 0.11457740867377075,
                            'rmse': 0.7987381565429623}],
          'tableTwoData': [{'predict': 193.4879556150843, 'year': 2010},
                           {'predict': 380.9130367903532, 'year': 2011},
                           {'predict': 307.76681293964435, 'year': 2012},
                           {'predict': 92.69408009209472, 'year': 2013},
                           {'predict': 125.92921966560257, 'year': 2014},
                           {'predict': 191.46582463437483, 'year': 2015},
                           {'predict': 406.8266479840512, 'year': 2016},
                           {'predict': 74.6314620982685, 'year': 2017},
                           {'predict': 109.94309646288562, 'year': 2018},
                           {'predict': 397.79711442897076, 'year': 2019},
                           {'predict': 83.62598493428752, 'year': 2020},
                           {'predict': 85.1243439937615, 'year': 2021},
                           {'predict': 150.60515682878923, 'year': 2022},
                           {'predict': 64.73402683925428, 'year': 2023},
                           {'predict': 276.4105045031033, 'year': 2024},
                           {'predict': 199.4081604516397, 'year': 2025},
                           {'predict': 144.97390559027943, 'year': 2026}]},
 'msg': 'success'}
