FORMAT: 1A

+ Response 200 (application/json)

# [/api/predict/region/mix]

## RegionMixPredict [POST]

{'code': 200,
 'data': {'graphData': [{'xName': '1', 'yValue': 500},
                        {'xName': '2', 'yValue': 500},
                        {'xName': '3', 'yValue': 500},
                        {'xName': '4', 'yValue': 500},
                        {'xName': '5', 'yValue': 500},
                        {'xName': '6', 'yValue': 500},
                        {'xName': '7', 'yValue': 500},
                        {'xName': '8', 'yValue': 500},
                        {'xName': '9', 'yValue': 500},
                        {'xName': '10', 'yValue': 500},
                        {'xName': '11', 'yValue': 500},
                        {'xName': '12', 'yValue': 500},
                        {'xName': '13', 'yValue': 500},
                        {'xName': '14', 'yValue': 500},
                        {'xName': '15', 'yValue': 500},
                        {'xName': '16', 'yValue': 500},
                        {'xName': '17', 'yValue': 500}],
          'tableOneData': [{'index': '评价指标 1',
                            'mape': 0.718281828,
                            'r2': 0.718281828,
                            'rmse': 0.718281828},
                           {'index': '评价指标 2',
                            'mape': 0.718281828,
                            'r2': 0.718281828,
                            'rmse': 0.718281828},
                           {'index': '评价指标 3',
                            'mape': 0.718281828,
                            'r2': 0.718281828,
                            'rmse': 0.718281828},
                           {'index': '评价指标 4',
                            'mape': 0.718281828,
                            'r2': 0.718281828,
                            'rmse': 0.718281828},
                           {'index': '评价指标 5',
                            'mape': 0.718281828,
                            'r2': 0.718281828,
                            'rmse': 0.718281828},
                           {'index': '评价指标 6',
                            'mape': 0.718281828,
                            'r2': 0.718281828,
                            'rmse': 0.718281828},
                           {'index': '评价指标 7',
                            'mape': 0.718281828,
                            'r2': 0.718281828,
                            'rmse': 0.718281828},
                           {'index': '评价指标 8',
                            'mape': 0.718281828,
                            'r2': 0.718281828,
                            'rmse': 0.718281828},
                           {'index': '评价指标 9',
                            'mape': 0.718281828,
                            'r2': 0.718281828,
                            'rmse': 0.718281828},
                           {'index': '评价指标 10',
                            'mape': 0.718281828,
                            'r2': 0.718281828,
                            'rmse': 0.718281828},
                           {'index': '评价指标 11',
                            'mape': 0.718281828,
                            'r2': 0.718281828,
                            'rmse': 0.718281828},
                           {'index': '评价指标 12',
                            'mape': 0.718281828,
                            'r2': 0.718281828,
                            'rmse': 0.718281828},
                           {'index': '评价指标 13',
                            'mape': 0.718281828,
                            'r2': 0.718281828,
                            'rmse': 0.718281828},
                           {'index': '评价指标 14',
                            'mape': 0.718281828,
                            'r2': 0.718281828,
                            'rmse': 0.718281828},
                           {'index': '评价指标 15',
                            'mape': 0.718281828,
                            'r2': 0.718281828,
                            'rmse': 0.718281828},
                           {'index': '评价指标 16',
                            'mape': 0.718281828,
                            'r2': 0.718281828,
                            'rmse': 0.718281828},
                           {'index': '评价指标 17',
                            'mape': 0.718281828,
                            'r2': 0.718281828,
                            'rmse': 0.718281828}],
          'tableTwoData': [{'predict': 287.3127312, 'year': 2010},
                           {'predict': 287.3127312, 'year': 2011},
                           {'predict': 287.3127312, 'year': 2012},
                           {'predict': 287.3127312, 'year': 2013},
                           {'predict': 287.3127312, 'year': 2014},
                           {'predict': 287.3127312, 'year': 2015},
                           {'predict': 287.3127312, 'year': 2016},
                           {'predict': 287.3127312, 'year': 2017},
                           {'predict': 287.3127312, 'year': 2018},
                           {'predict': 287.3127312, 'year': 2019},
                           {'predict': 287.3127312, 'year': 2020},
                           {'predict': 287.3127312, 'year': 2021},
                           {'predict': 287.3127312, 'year': 2022},
                           {'predict': 287.3127312, 'year': 2023},
                           {'predict': 287.3127312, 'year': 2024},
                           {'predict': 287.3127312, 'year': 2025},
                           {'predict': 287.3127312, 'year': 2026}]},
 'msg': 'success'}
