FORMAT: 1A

+ Response 200 (application/json)

# [/api/predict/region/single]
## RegionSinglePredict [POST]

{'code': 200,
 'data': {'graphData': [{'xName': '1', 'yValue': 30},
                        {'xName': '2', 'yValue': 141},
                        {'xName': '3', 'yValue': 104},
                        {'xName': '4', 'yValue': 999},
                        {'xName': '5', 'yValue': 279},
                        {'xName': '6', 'yValue': 433},
                        {'xName': '7', 'yValue': 897},
                        {'xName': '8', 'yValue': 279},
                        {'xName': '9', 'yValue': 720},
                        {'xName': '10', 'yValue': 512},
                        {'xName': '11', 'yValue': 225},
                        {'xName': '12', 'yValue': 946},
                        {'xName': '13', 'yValue': 174},
                        {'xName': '14', 'yValue': 250},
                        {'xName': '15', 'yValue': 975},
                        {'xName': '16', 'yValue': 844},
                        {'xName': '17', 'yValue': 735}],
          'tableOneData': [{'index': '评价指标 1',
                            'mape': 0.3714019643080684,
                            'r2': 0.45863608476495954,
                            'rmse': 0.7231599667195667},
                           {'index': '评价指标 2',
                            'mape': 0.6894035818119126,
                            'r2': 0.9293276869021627,
                            'rmse': 0.7749627057214725},
                           {'index': '评价指标 3',
                            'mape': 0.24920079045928778,
                            'r2': 0.06852868707220461,
                            'rmse': 0.36475572838942216},
                           {'index': '评价指标 4',
                            'mape': 0.04646794904055718,
                            'r2': 0.15106992287654952,
                            'rmse': 0.22136953809347126},
                           {'index': '评价指标 5',
                            'mape': 0.6419206009572501,
                            'r2': 0.3881299978795808,
                            'rmse': 0.34044337723286244},
                           {'index': '评价指标 6',
                            'mape': 0.7032926667496071,
                            'r2': 0.17128044718712832,
                            'rmse': 0.07940274086892662},
                           {'index': '评价指标 7',
                            'mape': 0.6171654069221998,
                            'r2': 0.462100761094721,
                            'rmse': 0.8906574254571399},
                           {'index': '评价指标 8',
                            'mape': 0.713700257167237,
                            'r2': 0.39391464471694704,
                            'rmse': 0.06857450994077674},
                           {'index': '评价指标 9',
                            'mape': 0.815873202096868,
                            'r2': 0.6417141766853534,
                            'rmse': 0.43992162241761956},
                           {'index': '评价指标 10',
                            'mape': 0.17013544540305348,
                            'r2': 0.9164135754516461,
                            'rmse': 0.22662391536227922},
                           {'index': '评价指标 11',
                            'mape': 0.5584524551012643,
                            'r2': 0.9578267278876662,
                            'rmse': 0.22472253019085253},
                           {'index': '评价指标 12',
                            'mape': 0.18873464127233208,
                            'r2': 0.569937047337519,
                            'rmse': 0.9519538532673176},
                           {'index': '评价指标 13',
                            'mape': 0.9529723462836517,
                            'r2': 0.451168492480844,
                            'rmse': 0.618750803944134},
                           {'index': '评价指标 14',
                            'mape': 0.41704855203786106,
                            'r2': 0.517897761753156,
                            'rmse': 0.1715418395248649},
                           {'index': '评价指标 15',
                            'mape': 0.6365080382357051,
                            'r2': 0.3192144236352289,
                            'rmse': 0.5067377000940074},
                           {'index': '评价指标 16',
                            'mape': 0.30094118772494993,
                            'r2': 0.7258207304515308,
                            'rmse': 0.7463903801571415},
                           {'index': '评价指标 17',
                            'mape': 0.15931754504010887,
                            'r2': 0.4966324465582742,
                            'rmse': 0.31081185282732826}],
          'tableTwoData': [{'predict': 245.8310359387107, 'year': 2010},
                           {'predict': 336.36263603220334, 'year': 2011},
                           {'predict': 70.44987826193007, 'year': 2012},
                           {'predict': 289.1712492316321, 'year': 2013},
                           {'predict': 253.70886301411508, 'year': 2014},
                           {'predict': 143.51295922824968, 'year': 2015},
                           {'predict': 169.1734275010655, 'year': 2016},
                           {'predict': 140.90411721162698, 'year': 2017},
                           {'predict': 301.01024090897744, 'year': 2018},
                           {'predict': 128.33320660813794, 'year': 2019},
                           {'predict': 376.129564365291, 'year': 2020},
                           {'predict': 34.85097613661628, 'year': 2021},
                           {'predict': 111.73500449454967, 'year': 2022},
                           {'predict': 197.27851499221424, 'year': 2023},
                           {'predict': 321.6376762719838, 'year': 2024},
                           {'predict': 14.521658044393266, 'year': 2025},
                           {'predict': 32.92186250955229, 'year': 2026}]},
 'msg': 'success'}
