FORMAT: 1A

+ Response 200 (application/json)

# [/api/predict/region/single]
## RegionSinglePredict [POST]

{'code': 200,
 'data': {'graphData': [{'xName': '1', 'yValue': 987},
                        {'xName': '2', 'yValue': 307},
                        {'xName': '3', 'yValue': 363},
                        {'xName': '4', 'yValue': 997},
                        {'xName': '5', 'yValue': 922},
                        {'xName': '6', 'yValue': 840},
                        {'xName': '7', 'yValue': 16},
                        {'xName': '8', 'yValue': 886},
                        {'xName': '9', 'yValue': 213},
                        {'xName': '10', 'yValue': 245},
                        {'xName': '11', 'yValue': 369},
                        {'xName': '12', 'yValue': 834},
                        {'xName': '13', 'yValue': 295},
                        {'xName': '14', 'yValue': 973},
                        {'xName': '15', 'yValue': 494},
                        {'xName': '16', 'yValue': 269},
                        {'xName': '17', 'yValue': 20}],
          'tableOneData': [{'index': '评价指标 1',
                            'mape': 0.5878866197113223,
                            'r2': 0.018194863688548946,
                            'rmse': 0.2747410285628219},
                           {'index': '评价指标 2',
                            'mape': 0.23963552327222293,
                            'r2': 0.5444534896542428,
                            'rmse': 0.5830950640041312},
                           {'index': '评价指标 3',
                            'mape': 0.8693171733405961,
                            'r2': 0.5299389147089244,
                            'rmse': 0.45402006674335194},
                           {'index': '评价指标 4',
                            'mape': 0.5309488565226083,
                            'r2': 0.42720527187662327,
                            'rmse': 0.350264499592462},
                           {'index': '评价指标 5',
                            'mape': 0.38437067965008553,
                            'r2': 0.8733080415875819,
                            'rmse': 0.20224756958832923},
                           {'index': '评价指标 6',
                            'mape': 0.7049253109710618,
                            'r2': 0.4521247448712513,
                            'rmse': 0.3176484280945011},
                           {'index': '评价指标 7',
                            'mape': 0.7114782363001394,
                            'r2': 0.6113194673478595,
                            'rmse': 0.43539501604425146},
                           {'index': '评价指标 8',
                            'mape': 0.5476965598409533,
                            'r2': 0.23826290358277302,
                            'rmse': 0.7050767915793371},
                           {'index': '评价指标 9',
                            'mape': 0.9156267389839671,
                            'r2': 0.5588279734453742,
                            'rmse': 0.043176293346975925},
                           {'index': '评价指标 10',
                            'mape': 0.10548007589392305,
                            'r2': 0.47142580268353385,
                            'rmse': 0.18814398429215995},
                           {'index': '评价指标 11',
                            'mape': 0.11216569869135273,
                            'r2': 0.9331549943914839,
                            'rmse': 0.9041281111945911},
                           {'index': '评价指标 12',
                            'mape': 0.770913751398232,
                            'r2': 0.05053000888213566,
                            'rmse': 0.400080418101208},
                           {'index': '评价指标 13',
                            'mape': 0.2224266717877399,
                            'r2': 0.43246503097034217,
                            'rmse': 0.4423522396516322},
                           {'index': '评价指标 14',
                            'mape': 0.3923995590719249,
                            'r2': 0.7358430338269302,
                            'rmse': 0.9745030702498693},
                           {'index': '评价指标 15',
                            'mape': 0.4434988027640059,
                            'r2': 0.572247464894794,
                            'rmse': 0.8000056299873454},
                           {'index': '评价指标 16',
                            'mape': 0.3476110243081171,
                            'r2': 0.8750742635774181,
                            'rmse': 0.6919244590436682},
                           {'index': '评价指标 17',
                            'mape': 0.744788252386765,
                            'r2': 0.6363531405495926,
                            'rmse': 0.6568842927318768}],
          'tableTwoData': [{'predict': 39.466707631613694, 'year': 2010},
                           {'predict': 251.43047158190842, 'year': 2011},
                           {'predict': 171.10080491036757, 'year': 2012},
                           {'predict': 265.6201175168598, 'year': 2013},
                           {'predict': 96.7320890587847, 'year': 2014},
                           {'predict': 302.3107129259718, 'year': 2015},
                           {'predict': 207.3822863444635, 'year': 2016},
                           {'predict': 81.75851440533545, 'year': 2017},
                           {'predict': 109.86445921904422, 'year': 2018},
                           {'predict': 249.3689000087848, 'year': 2019},
                           {'predict': 82.92919889284916, 'year': 2020},
                           {'predict': 206.17628236579665, 'year': 2021},
                           {'predict': 248.48285682687458, 'year': 2022},
                           {'predict': 314.1170011574981, 'year': 2023},
                           {'predict': 121.1330502777341, 'year': 2024},
                           {'predict': 292.8645261128016, 'year': 2025},
                           {'predict': 122.33042966557899, 'year': 2026}]},
 'msg': 'success'}
