FORMAT: 1A

+ Response 200 (application/json)

# [/api/method/region/query]

## RegionalMethodQuery [GET]

{'code': 200,
 'data': ['逐步回归模型',
          '灰色滑动平均模型',
          '分数阶灰色模型',
          '改进的滚动机理灰色预测',
          '高斯混合回归模型',
          '模糊线性回归模型',
          '模糊指数平滑模型',
          '梯度提升模型',
          '支持向量机模型',
          '循环神经网络模型',
          '长短期神经网络模型',
          '扩展索洛模型',
          '分位数回归模型',
          '分行业典型日负荷曲线叠加法',
          '负荷最大利用小时数模型',
          '季节趋势模型',
          '考虑温度和节假日分布影响的电量预测模型',
          '一元线性函数',
          '一元二次函数',
          '幂函数',
          '生长函数',
          '指数函数',
          '对数函数',
          '二元一次函数'],
 'msg': 'success'}
