FORMAT: 1A

+ Response 200 (application/json)

# [/api/predict/region/mix]
## RegionMixPredict [POST]

{'code': 200,
 'data': {'graphData': [{'xName': '1', 'yValue': 688},
                        {'xName': '2', 'yValue': 633},
                        {'xName': '3', 'yValue': 698},
                        {'xName': '4', 'yValue': 722},
                        {'xName': '5', 'yValue': 806},
                        {'xName': '6', 'yValue': 997},
                        {'xName': '7', 'yValue': 85},
                        {'xName': '8', 'yValue': 630},
                        {'xName': '9', 'yValue': 380},
                        {'xName': '10', 'yValue': 381},
                        {'xName': '11', 'yValue': 539},
                        {'xName': '12', 'yValue': 591},
                        {'xName': '13', 'yValue': 385},
                        {'xName': '14', 'yValue': 20},
                        {'xName': '15', 'yValue': 662},
                        {'xName': '16', 'yValue': 794},
                        {'xName': '17', 'yValue': 70}],
          'tableOneData': [{'index': '评价指标 1',
                            'mape': 0.9278492825767009,
                            'r2': 0.5618660187883686,
                            'rmse': 0.1494369457031508},
                           {'index': '评价指标 2',
                            'mape': 0.8898453130147468,
                            'r2': 0.5690582365893192,
                            'rmse': 0.6747516891165125},
                           {'index': '评价指标 3',
                            'mape': 0.9238303850402563,
                            'r2': 0.459571633574018,
                            'rmse': 0.47068659884062114},
                           {'index': '评价指标 4',
                            'mape': 0.08149573037585955,
                            'r2': 0.25869391160221866,
                            'rmse': 0.2942265171437718},
                           {'index': '评价指标 5',
                            'mape': 0.33267560722181144,
                            'r2': 0.3803259605806766,
                            'rmse': 0.028048622457836236},
                           {'index': '评价指标 6',
                            'mape': 0.8855446971283039,
                            'r2': 0.372340836167512,
                            'rmse': 0.23077598147329892},
                           {'index': '评价指标 7',
                            'mape': 0.4523470673045582,
                            'r2': 0.5345981006972004,
                            'rmse': 0.3516152779671866},
                           {'index': '评价指标 8',
                            'mape': 0.346031873204515,
                            'r2': 0.08583331368735991,
                            'rmse': 0.7851658569208176},
                           {'index': '评价指标 9',
                            'mape': 0.022797333489987026,
                            'r2': 0.2212922687054758,
                            'rmse': 0.6067953960340695},
                           {'index': '评价指标 10',
                            'mape': 0.7552311491141153,
                            'r2': 0.29437453532740876,
                            'rmse': 0.197299997309612},
                           {'index': '评价指标 11',
                            'mape': 0.4657102938539813,
                            'r2': 0.7209277342363092,
                            'rmse': 0.5689255901915126},
                           {'index': '评价指标 12',
                            'mape': 0.7965351985031688,
                            'r2': 0.3076782364374854,
                            'rmse': 0.6028484824639166},
                           {'index': '评价指标 13',
                            'mape': 0.07647083786608277,
                            'r2': 0.2048232549947404,
                            'rmse': 0.49397983713888016},
                           {'index': '评价指标 14',
                            'mape': 0.7130716837991086,
                            'r2': 0.14359902558665683,
                            'rmse': 0.11859546337816518},
                           {'index': '评价指标 15',
                            'mape': 0.5394003990593675,
                            'r2': 0.771295387191158,
                            'rmse': 0.8150499915690357},
                           {'index': '评价指标 16',
                            'mape': 0.7959767744131429,
                            'r2': 0.719183841317562,
                            'rmse': 0.9758567403091544},
                           {'index': '评价指标 17',
                            'mape': 0.6356789489760608,
                            'r2': 0.4291230867311171,
                            'rmse': 0.10072908753906185}],
          'tableTwoData': [{'predict': 66.63024612769071, 'year': 2010},
                           {'predict': 188.4351107433143, 'year': 2011},
                           {'predict': 103.23729840510401, 'year': 2012},
                           {'predict': 138.64606427915737, 'year': 2013},
                           {'predict': 200.9945561934137, 'year': 2014},
                           {'predict': 107.25848575208008, 'year': 2015},
                           {'predict': 117.34634274130045, 'year': 2016},
                           {'predict': 106.73373777275494, 'year': 2017},
                           {'predict': 135.6189078049525, 'year': 2018},
                           {'predict': 182.29280364480698, 'year': 2019},
                           {'predict': 409.9756175993749, 'year': 2020},
                           {'predict': 16.42493974521878, 'year': 2021},
                           {'predict': 252.5273493405902, 'year': 2022},
                           {'predict': 54.81715937295183, 'year': 2023},
                           {'predict': 217.06837143182494, 'year': 2024},
                           {'predict': 122.50435329835246, 'year': 2025},
                           {'predict': 355.0229784492434, 'year': 2026}]},
 'msg': 'success'}
