FORMAT: 1A

+ Response 200 (application/json)

# [/api/predict/saturation]
## SaturationCurvePredict [POST]

{'code': 200,
 'data': {'graphData': [{'xName': '1', 'yValue': 788},
                        {'xName': '2', 'yValue': 502},
                        {'xName': '3', 'yValue': 631},
                        {'xName': '4', 'yValue': 468},
                        {'xName': '5', 'yValue': 161},
                        {'xName': '6', 'yValue': 293},
                        {'xName': '7', 'yValue': 779},
                        {'xName': '8', 'yValue': 2},
                        {'xName': '9', 'yValue': 293},
                        {'xName': '10', 'yValue': 498},
                        {'xName': '11', 'yValue': 838},
                        {'xName': '12', 'yValue': 25},
                        {'xName': '13', 'yValue': 906},
                        {'xName': '14', 'yValue': 617},
                        {'xName': '15', 'yValue': 92},
                        {'xName': '16', 'yValue': 666},
                        {'xName': '17', 'yValue': 324}],
          'tableOneData': [{'index': '评价指标 1',
                            'mape': 0.5164014440251915,
                            'r2': 0.8597483117933609,
                            'rmse': 0.791083440172428},
                           {'index': '评价指标 2',
                            'mape': 0.09751810130008187,
                            'r2': 0.3267310474966981,
                            'rmse': 0.5134696069192},
                           {'index': '评价指标 3',
                            'mape': 0.0052915509687980755,
                            'r2': 0.5473696288950359,
                            'rmse': 0.6659674988329175},
                           {'index': '评价指标 4',
                            'mape': 0.6414462219344125,
                            'r2': 0.3095083142664443,
                            'rmse': 0.6663918070099982},
                           {'index': '评价指标 5',
                            'mape': 0.19880504578098845,
                            'r2': 0.07889579191311957,
                            'rmse': 0.6485141584574505},
                           {'index': '评价指标 6',
                            'mape': 0.6937812870567827,
                            'r2': 0.8457336673860473,
                            'rmse': 0.07369230533753635},
                           {'index': '评价指标 7',
                            'mape': 0.43901275609931134,
                            'r2': 0.3376281671739083,
                            'rmse': 0.8517527102668038},
                           {'index': '评价指标 8',
                            'mape': 0.734872146325418,
                            'r2': 0.1554586565412449,
                            'rmse': 0.7605406194351897},
                           {'index': '评价指标 9',
                            'mape': 0.7277143459198534,
                            'r2': 0.21330575561736675,
                            'rmse': 0.7623520588570153},
                           {'index': '评价指标 10',
                            'mape': 0.8462335761953349,
                            'r2': 0.2225455996739656,
                            'rmse': 0.5699101773704777},
                           {'index': '评价指标 11',
                            'mape': 0.29093335653106767,
                            'r2': 0.29282555411197453,
                            'rmse': 0.6666194874449097},
                           {'index': '评价指标 12',
                            'mape': 0.08180895875710403,
                            'r2': 0.30092035235125825,
                            'rmse': 0.23912571573111074},
                           {'index': '评价指标 13',
                            'mape': 0.9998527723641136,
                            'r2': 0.948972977232458,
                            'rmse': 0.6271758228735567},
                           {'index': '评价指标 14',
                            'mape': 0.16713178760436864,
                            'r2': 0.6711270957058764,
                            'rmse': 0.46737422393870875},
                           {'index': '评价指标 15',
                            'mape': 0.4377257264806791,
                            'r2': 0.474072448361071,
                            'rmse': 0.2527957152037589},
                           {'index': '评价指标 16',
                            'mape': 0.9739230579883529,
                            'r2': 0.30192424271830276,
                            'rmse': 0.7453210322014785},
                           {'index': '评价指标 17',
                            'mape': 0.28009065140065614,
                            'r2': 0.6867041746330672,
                            'rmse': 0.1431061229300029}],
          'tableTwoData': [{'predict': 423.00261647922406, 'year': 2010},
                           {'predict': 353.5064693988474, 'year': 2011},
                           {'predict': 173.0522209737954, 'year': 2012},
                           {'predict': 59.58993829808614, 'year': 2013},
                           {'predict': 330.9431102614634, 'year': 2014},
                           {'predict': 361.00148171364566, 'year': 2015},
                           {'predict': 169.87941986753793, 'year': 2016},
                           {'predict': 262.02072208224956, 'year': 2017},
                           {'predict': 125.02170596890687, 'year': 2018},
                           {'predict': 41.37236233902681, 'year': 2019},
                           {'predict': 208.74535003322515, 'year': 2020},
                           {'predict': 209.13659233278148, 'year': 2021},
                           {'predict': 172.20073811251692, 'year': 2022},
                           {'predict': 193.01789306684552, 'year': 2023},
                           {'predict': 133.94359384392413, 'year': 2024},
                           {'predict': 314.42376100908734, 'year': 2025},
                           {'predict': 281.52990485963016, 'year': 2026}]},
 'msg': 'success'}
