FORMAT: 1A

+ Response 200 (application/json)

# [/api/predict/saturation]
## SaturationCurvePredict [POST]

{'code': 200,
 'data': {'graphData': [{'xName': '1', 'yValue': 761},
                        {'xName': '2', 'yValue': 677},
                        {'xName': '3', 'yValue': 708},
                        {'xName': '4', 'yValue': 935},
                        {'xName': '5', 'yValue': 576},
                        {'xName': '6', 'yValue': 192},
                        {'xName': '7', 'yValue': 811},
                        {'xName': '8', 'yValue': 887},
                        {'xName': '9', 'yValue': 196},
                        {'xName': '10', 'yValue': 859},
                        {'xName': '11', 'yValue': 427},
                        {'xName': '12', 'yValue': 513},
                        {'xName': '13', 'yValue': 192},
                        {'xName': '14', 'yValue': 339},
                        {'xName': '15', 'yValue': 660},
                        {'xName': '16', 'yValue': 970},
                        {'xName': '17', 'yValue': 522}],
          'tableOneData': [{'index': '评价指标 1',
                            'mape': 0.46803235381616615,
                            'r2': 0.05782501514165672,
                            'rmse': 0.24747122124253562},
                           {'index': '评价指标 2',
                            'mape': 0.7326561354512268,
                            'r2': 0.725929486691626,
                            'rmse': 0.20362400856470253},
                           {'index': '评价指标 3',
                            'mape': 0.4626523838417559,
                            'r2': 0.07556961323592715,
                            'rmse': 0.9334397243225439},
                           {'index': '评价指标 4',
                            'mape': 0.9476662664629103,
                            'r2': 0.2761781879203389,
                            'rmse': 0.25394966214813375},
                           {'index': '评价指标 5',
                            'mape': 0.3711809547289594,
                            'r2': 0.6456226904587923,
                            'rmse': 0.8108200618326645},
                           {'index': '评价指标 6',
                            'mape': 0.4768879035684269,
                            'r2': 0.7725323181535863,
                            'rmse': 0.86115341240916},
                           {'index': '评价指标 7',
                            'mape': 0.5481537154538054,
                            'r2': 0.8113771249096561,
                            'rmse': 0.2751319703036458},
                           {'index': '评价指标 8',
                            'mape': 0.10258653061615242,
                            'r2': 0.1144072256553148,
                            'rmse': 0.03883000409385229},
                           {'index': '评价指标 9',
                            'mape': 0.0840561125742183,
                            'r2': 0.689198518337645,
                            'rmse': 0.4426724741717605},
                           {'index': '评价指标 10',
                            'mape': 0.7727452649024934,
                            'r2': 0.32220538185232805,
                            'rmse': 0.45799177549394643},
                           {'index': '评价指标 11',
                            'mape': 0.7638939652456674,
                            'r2': 0.22825072729772167,
                            'rmse': 0.4733956033027278},
                           {'index': '评价指标 12',
                            'mape': 0.6315089833352681,
                            'r2': 0.6112766251194659,
                            'rmse': 0.26739458127430626},
                           {'index': '评价指标 13',
                            'mape': 0.6588702833663738,
                            'r2': 0.5325916983892783,
                            'rmse': 0.8596859088010579},
                           {'index': '评价指标 14',
                            'mape': 0.5044023611592124,
                            'r2': 0.22756117047679336,
                            'rmse': 0.5504165166222732},
                           {'index': '评价指标 15',
                            'mape': 0.09628813097392697,
                            'r2': 0.26211150304191044,
                            'rmse': 0.26322646843510233},
                           {'index': '评价指标 16',
                            'mape': 0.5541978036062856,
                            'r2': 0.6391328528686571,
                            'rmse': 0.30550596268149166},
                           {'index': '评价指标 17',
                            'mape': 0.36134627739069136,
                            'r2': 0.8084527533081438,
                            'rmse': 0.32233756979835604}],
          'tableTwoData': [{'predict': 212.03358175544724, 'year': 2010},
                           {'predict': 229.39290284753125, 'year': 2011},
                           {'predict': 80.43415412395964, 'year': 2012},
                           {'predict': 259.3376602942498, 'year': 2013},
                           {'predict': 292.2050190586001, 'year': 2014},
                           {'predict': 293.8603273837071, 'year': 2015},
                           {'predict': 387.9698249135105, 'year': 2016},
                           {'predict': 198.2694789164399, 'year': 2017},
                           {'predict': 203.01689376433305, 'year': 2018},
                           {'predict': 24.290606392373697, 'year': 2019},
                           {'predict': 230.6335312103647, 'year': 2020},
                           {'predict': 411.62307779876613, 'year': 2021},
                           {'predict': 161.97399237406057, 'year': 2022},
                           {'predict': 376.9501437593762, 'year': 2023},
                           {'predict': 144.58008715484863, 'year': 2024},
                           {'predict': 179.0261054294367, 'year': 2025},
                           {'predict': 295.0079639074403, 'year': 2026}]},
 'msg': 'success'}
