FORMAT: 1A

+ Response 200 (application/json)

# [/api/predict/saturation]
## SaturationCurvePredict [POST]

{'code': 200,
 'data': {'graphData': [{'xName': '1', 'yValue': 440},
                        {'xName': '2', 'yValue': 290},
                        {'xName': '3', 'yValue': 774},
                        {'xName': '4', 'yValue': 187},
                        {'xName': '5', 'yValue': 74},
                        {'xName': '6', 'yValue': 795},
                        {'xName': '7', 'yValue': 646},
                        {'xName': '8', 'yValue': 157},
                        {'xName': '9', 'yValue': 257},
                        {'xName': '10', 'yValue': 689},
                        {'xName': '11', 'yValue': 972},
                        {'xName': '12', 'yValue': 812},
                        {'xName': '13', 'yValue': 473},
                        {'xName': '14', 'yValue': 303},
                        {'xName': '15', 'yValue': 675},
                        {'xName': '16', 'yValue': 795},
                        {'xName': '17', 'yValue': 618}],
          'tableOneData': [{'index': '评价指标 1',
                            'mape': 0.6089127661781557,
                            'r2': 0.5072412287960973,
                            'rmse': 0.26581110002697617},
                           {'index': '评价指标 2',
                            'mape': 0.9541931673035816,
                            'r2': 0.9469756366242499,
                            'rmse': 0.4859578616595668},
                           {'index': '评价指标 3',
                            'mape': 0.1246741950673963,
                            'r2': 0.6289038995683586,
                            'rmse': 0.9527501069586816},
                           {'index': '评价指标 4',
                            'mape': 0.05073609106139676,
                            'r2': 0.5173761743659214,
                            'rmse': 0.36956228383412426},
                           {'index': '评价指标 5',
                            'mape': 0.002978384563959602,
                            'r2': 0.6187324880869401,
                            'rmse': 0.46619868434274714},
                           {'index': '评价指标 6',
                            'mape': 0.45721655852809195,
                            'r2': 0.5053229477524469,
                            'rmse': 0.3646046281846659},
                           {'index': '评价指标 7',
                            'mape': 0.3205192722108261,
                            'r2': 0.9518012380890745,
                            'rmse': 0.8032380244678361},
                           {'index': '评价指标 8',
                            'mape': 0.40029337365905493,
                            'r2': 0.526489302638034,
                            'rmse': 0.6221365222985497},
                           {'index': '评价指标 9',
                            'mape': 0.4187656552529325,
                            'r2': 0.42457149639077074,
                            'rmse': 0.3875635416468478},
                           {'index': '评价指标 10',
                            'mape': 0.37871209869896794,
                            'r2': 0.9959826469003753,
                            'rmse': 0.6829702962835337},
                           {'index': '评价指标 11',
                            'mape': 0.07479937764902511,
                            'r2': 0.5213795141277062,
                            'rmse': 0.009087826870309179},
                           {'index': '评价指标 12',
                            'mape': 0.9903573480355238,
                            'r2': 0.08376664459561167,
                            'rmse': 0.5336224281337567},
                           {'index': '评价指标 13',
                            'mape': 0.6905915191569276,
                            'r2': 0.6332474921561029,
                            'rmse': 0.12166856566365247},
                           {'index': '评价指标 14',
                            'mape': 0.49840578662582435,
                            'r2': 0.2265290496751029,
                            'rmse': 0.368797790637471},
                           {'index': '评价指标 15',
                            'mape': 0.12204597449668075,
                            'r2': 0.8877987004490692,
                            'rmse': 0.7202759827894339},
                           {'index': '评价指标 16',
                            'mape': 0.6324157208409587,
                            'r2': 0.04238379892269151,
                            'rmse': 0.9445755706803421},
                           {'index': '评价指标 17',
                            'mape': 0.3376139714107105,
                            'r2': 0.6916859583129933,
                            'rmse': 0.06720772434008004}],
          'tableTwoData': [{'predict': 285.6130237992859, 'year': 2010},
                           {'predict': 170.20118916880082, 'year': 2011},
                           {'predict': 71.52352508130318, 'year': 2012},
                           {'predict': 237.87818921837024, 'year': 2013},
                           {'predict': 169.6114929392885, 'year': 2014},
                           {'predict': 36.76282570869423, 'year': 2015},
                           {'predict': 296.5626765534077, 'year': 2016},
                           {'predict': 44.88645199589481, 'year': 2017},
                           {'predict': 421.18184223682107, 'year': 2018},
                           {'predict': 148.2344485046214, 'year': 2019},
                           {'predict': 249.77382997512066, 'year': 2020},
                           {'predict': 369.46992934002753, 'year': 2021},
                           {'predict': 366.07625645910866, 'year': 2022},
                           {'predict': 51.84895883418428, 'year': 2023},
                           {'predict': 382.01236162283686, 'year': 2024},
                           {'predict': 234.72886801915888, 'year': 2025},
                           {'predict': 50.98937663080011, 'year': 2026}]},
 'msg': 'success'}
