FORMAT: 1A

+ Response 200 (application/json)

# [/api/payload/predict/dbquery]
## SokuPayloadPredict [POST]

{'code': 200,
 'data': [{'actualPayload': 372256, 'predictPayload': 853585, 'time': '11:16'},
          {'actualPayload': 510225, 'predictPayload': 465635, 'time': '10:15'},
          {'actualPayload': 391296, 'predictPayload': 922241, 'time': '17:31'},
          {'actualPayload': 167042, 'predictPayload': 178230, 'time': '15:20'},
          {'actualPayload': 875847, 'predictPayload': 363797, 'time': '11:46'},
          {'actualPayload': 385814, 'predictPayload': 68296, 'time': '13:50'},
          {'actualPayload': 909630, 'predictPayload': 679372, 'time': '20:15'},
          {'actualPayload': 664206, 'predictPayload': 579753, 'time': '16:13'},
          {'actualPayload': 264174, 'predictPayload': 394283, 'time': '20:37'},
          {'actualPayload': 70771, 'predictPayload': 87874, 'time': '13:36'},
          {'actualPayload': 666240, 'predictPayload': 733809, 'time': '17:29'},
          {'actualPayload': 160935, 'predictPayload': 85412, 'time': '19:24'}],
 'msg': 'success'}
