FORMAT: 1A

+ Response 200 (application/json)

# [/api/payload/predict/dbquery]
## SokuPayloadPredict [POST]

{'code': 200,
 'data': [{'actualPayload': 207090, 'predictPayload': 588219, 'time': '16:29'},
          {'actualPayload': 673361, 'predictPayload': 106018, 'time': '15:14'},
          {'actualPayload': 533662, 'predictPayload': 922242, 'time': '19:30'},
          {'actualPayload': 269012, 'predictPayload': 751694, 'time': '12:31'},
          {'actualPayload': 856034, 'predictPayload': 643181, 'time': '15:38'},
          {'actualPayload': 692540, 'predictPayload': 715395, 'time': '14:17'},
          {'actualPayload': 357546, 'predictPayload': 485293, 'time': '17:24'},
          {'actualPayload': 338320, 'predictPayload': 300054, 'time': '18:31'},
          {'actualPayload': 644528, 'predictPayload': 909284, 'time': '17:17'},
          {'actualPayload': 929345, 'predictPayload': 765701, 'time': '15:15'},
          {'actualPayload': 164394, 'predictPayload': 490673, 'time': '10:42'},
          {'actualPayload': 23529, 'predictPayload': 769883, 'time': '20:25'}],
 'msg': 'success'}
