FORMAT: 1A

+ Response 200 (application/json)

# [/api/params/predict/soku]
## SokuPayloadPredictionParameters [GET]

{'code': 200,
 'data': {'beginYear': 0,
          'beta': 0,
          'dailyAmount': 0,
          'endYear': 0,
          'gamma': 0,
          'maxPayload': 0,
          'season': 0},
 'msg': 'success'}
