FORMAT: 1A

+ Response 200 (application/json)

# [/api/params/predict/soku]
## SokuPayloadPredictionParameters [GET]

{'code': 200,
 'data': {'beginYear': 1955,
          'beta': 0.777,
          'dailyAmount': 1000,
          'endYear': 2055,
          'gamma': 0.555,
          'maxPayload': 2033,
          'season': 3},
 'msg': 'success'}
