FORMAT: 1A

+ Response 200 (application/json)

# [/api/payload/predict/dbquery]
## SokuPayloadPredict [POST]

{'code': 200,
 'data': [{'actualPayload': 857691, 'predictPayload': 245646, 'time': '12:47'},
          {'actualPayload': 71044, 'predictPayload': 787077, 'time': '11:14'},
          {'actualPayload': 257719, 'predictPayload': 336479, 'time': '20:13'},
          {'actualPayload': 655719, 'predictPayload': 759352, 'time': '14:12'},
          {'actualPayload': 610031, 'predictPayload': 735121, 'time': '14:27'},
          {'actualPayload': 184739, 'predictPayload': 663520, 'time': '10:32'},
          {'actualPayload': 988545, 'predictPayload': 354128, 'time': '19:21'},
          {'actualPayload': 196032, 'predictPayload': 260776, 'time': '12:40'},
          {'actualPayload': 721024, 'predictPayload': 561176, 'time': '10:23'},
          {'actualPayload': 788348, 'predictPayload': 703236, 'time': '16:30'},
          {'actualPayload': 242289, 'predictPayload': 199994, 'time': '11:13'},
          {'actualPayload': 173720, 'predictPayload': 316160, 'time': '18:18'}],
 'msg': 'success'}
