FORMAT: 1A

+ Response 200 (application/json)

# [/api/params/predict/static/region]
## StaticRegionalPredictionParameters [GET]

{'code': 200,
 'data': {'beginYear': 0,
          'endYear': 0,
          'factor1': {'hasValue': True, 'name': '', 'value': 0.5},
          'factor2': {'hasValue': True, 'name': '', 'value': 0.5},
          'historyBeginYear': 0,
          'historyEndYear': 0,
          'industry': '',
          'method': '',
          'region': ''},
 'msg': 'success'}
