FORMAT: 1A

+ Response 200 (application/json)

# [/api/params/predict/static/region]
## StaticRegionalPredictionParameters [GET]

{'code': 200,
 'data': {'beginYear': 2023,
          'endYear': 2033,
          'factor1': {'hasValue': True, 'name': 'MINGZI', 'value': 0.1},
          'factor2': {'hasValue': True, 'name': 'MINGZI2', 'value': 0.9},
          'historyBeginYear': 1999,
          'historyEndYear': 2009,
          'industry': '行业',
          'method': '方法',
          'region': '地域'},
 'msg': 'success'}
