FORMAT: 1A

+ Response 200 (application/json)

# [/api/payload/predict/yearly]
## YearlyContinuousPayloadPredict [POST]

{'code': 200,
 'data': [{'payload': 132096, 'time': '10:27'},
          {'payload': 648188, 'time': '19:33'},
          {'payload': 702304, 'time': '18:29'},
          {'payload': 419229, 'time': '15:25'},
          {'payload': 964978, 'time': '16:40'},
          {'payload': 906849, 'time': '17:31'},
          {'payload': 171239, 'time': '13:35'},
          {'payload': 707407, 'time': '18:30'},
          {'payload': 995866, 'time': '12:16'},
          {'payload': 331031, 'time': '10:24'},
          {'payload': 362087, 'time': '16:50'},
          {'payload': 45040, 'time': '15:24'}],
 'msg': 'success'}
