FORMAT: 1A

+ Response 200 (application/json)

# [/api/params/predict/yearcont]
## YearlyContinuousPayloadPrediction [GET]

{'code': 200,
 'data': {'beginYear': 0, 'endYear': 0, 'maxPayload': 0},
 'msg': 'success'}
