FORMAT: 1A

+ Response 200 (application/json)

# [/api/params/predict/yearcont]
## YearlyContinuousPayloadPredictionParameters [GET]

{'code': 200,
 'data': {'beginYear': 2023, 'endYear': 2033, 'maxPayload': 98768},
 'msg': 'success'}
