FORMAT: 1A

+ Response 200 (application/json)

# [/api/payload/predict/yearly]
## YearlyContinuousPayloadPredict [POST]

{'code': 200,
 'data': [{'payload': 841675, 'time': '10:39'},
          {'payload': 173695, 'time': '13:15'},
          {'payload': 17697, 'time': '10:23'},
          {'payload': 696737, 'time': '17:44'},
          {'payload': 963800, 'time': '11:44'},
          {'payload': 319881, 'time': '20:45'},
          {'payload': 876593, 'time': '19:21'},
          {'payload': 159159, 'time': '18:15'},
          {'payload': 856458, 'time': '13:19'},
          {'payload': 658343, 'time': '18:26'},
          {'payload': 361314, 'time': '19:21'},
          {'payload': 875178, 'time': '10:14'}],
 'msg': 'success'}
