FORMAT: 1A

+ Response 200 (application/json)

# [/api/payload/predict/yearly]
## YearlyContinuousPayloadPredict [POST]

{'code': 200,
 'data': [{'payload': 504965, 'time': '19:18'},
          {'payload': 528422, 'time': '14:40'},
          {'payload': 875841, 'time': '19:12'},
          {'payload': 35337, 'time': '14:15'},
          {'payload': 368716, 'time': '12:35'},
          {'payload': 668630, 'time': '15:20'},
          {'payload': 12022, 'time': '13:46'},
          {'payload': 715889, 'time': '13:10'},
          {'payload': 427621, 'time': '18:25'},
          {'payload': 800687, 'time': '13:42'},
          {'payload': 402812, 'time': '13:24'},
          {'payload': 825360, 'time': '11:42'}],
 'msg': 'success'}
